set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(CMAKE_C_FLAGS_INIT "-arch x86_64")
set(CMAKE_CXX_FLAGS_INIT "-arch x86_64")

set(STRIP_COMMAND strip)
set(PLATFORM_NAME macos-x64)

set(CMAKE_OSX_ARCHITECTURES x86_64 CACHE STRING "Build architectures for macOS")
