#ifndef GARLIC_JVM_INS_HELPER_H
#define GARLIC_JVM_INS_HELPER_H

#include "decompiler/structure.h"

#define DEFINE_INS_HELPER_METHOD(opcode, code_name) \
    static inline bool                              \
    jvm_ins_is_##code_name(jd_ins *ins)             \
    {                                               \
        return ins->code == opcode;                 \
    }

DEFINE_INS_HELPER_METHOD(0x00, nop               );
DEFINE_INS_HELPER_METHOD(0x01, aconst_null       );
DEFINE_INS_HELPER_METHOD(0x02, iconst_m1         );
DEFINE_INS_HELPER_METHOD(0x03, iconst_0          );
DEFINE_INS_HELPER_METHOD(0x04, iconst_1          );
DEFINE_INS_HELPER_METHOD(0x05, iconst_2          );
DEFINE_INS_HELPER_METHOD(0x06, iconst_3          );
DEFINE_INS_HELPER_METHOD(0x07, iconst_4          );
DEFINE_INS_HELPER_METHOD(0x08, iconst_5          );
DEFINE_INS_HELPER_METHOD(0x09, lconst_0          );
DEFINE_INS_HELPER_METHOD(0x0a, lconst_1          );
DEFINE_INS_HELPER_METHOD(0x0b, fconst_0          );
DEFINE_INS_HELPER_METHOD(0x0c, fconst_1          );
DEFINE_INS_HELPER_METHOD(0x0d, fconst_2          );
DEFINE_INS_HELPER_METHOD(0x0e, dconst_0          );
DEFINE_INS_HELPER_METHOD(0x0f, dconst_1          );
DEFINE_INS_HELPER_METHOD(0x10, bipush            );
DEFINE_INS_HELPER_METHOD(0x11, sipush            );
DEFINE_INS_HELPER_METHOD(0x12, ldc               );
DEFINE_INS_HELPER_METHOD(0x13, ldc_w             );
DEFINE_INS_HELPER_METHOD(0x14, ldc2_w            );
DEFINE_INS_HELPER_METHOD(0x15, iload             );
DEFINE_INS_HELPER_METHOD(0x16, lload             );
DEFINE_INS_HELPER_METHOD(0x17, fload             );
DEFINE_INS_HELPER_METHOD(0x18, dload             );
DEFINE_INS_HELPER_METHOD(0x19, aload             );
DEFINE_INS_HELPER_METHOD(0x1a, iload_0           );
DEFINE_INS_HELPER_METHOD(0x1b, iload_1           );
DEFINE_INS_HELPER_METHOD(0x1c, iload_2           );
DEFINE_INS_HELPER_METHOD(0x1d, iload_3           );
DEFINE_INS_HELPER_METHOD(0x1e, lload_0           );
DEFINE_INS_HELPER_METHOD(0x1f, lload_1           );
DEFINE_INS_HELPER_METHOD(0x20, lload_2           );
DEFINE_INS_HELPER_METHOD(0x21, lload_3           );
DEFINE_INS_HELPER_METHOD(0x22, fload_0           );
DEFINE_INS_HELPER_METHOD(0x23, fload_1           );
DEFINE_INS_HELPER_METHOD(0x24, fload_2           );
DEFINE_INS_HELPER_METHOD(0x25, fload_3           );
DEFINE_INS_HELPER_METHOD(0x26, dload_0           );
DEFINE_INS_HELPER_METHOD(0x27, dload_1           );
DEFINE_INS_HELPER_METHOD(0x28, dload_2           );
DEFINE_INS_HELPER_METHOD(0x29, dload_3           );
DEFINE_INS_HELPER_METHOD(0x2a, aload_0           );
DEFINE_INS_HELPER_METHOD(0x2b, aload_1           );
DEFINE_INS_HELPER_METHOD(0x2c, aload_2           );
DEFINE_INS_HELPER_METHOD(0x2d, aload_3           );
DEFINE_INS_HELPER_METHOD(0x2e, iaload            );
DEFINE_INS_HELPER_METHOD(0x2f, laload            );
DEFINE_INS_HELPER_METHOD(0x30, faload            );
DEFINE_INS_HELPER_METHOD(0x31, daload            );
DEFINE_INS_HELPER_METHOD(0x32, aaload            );
DEFINE_INS_HELPER_METHOD(0x33, baload            );
DEFINE_INS_HELPER_METHOD(0x34, caload            );
DEFINE_INS_HELPER_METHOD(0x35, saload            );
DEFINE_INS_HELPER_METHOD(0x36, istore            );
DEFINE_INS_HELPER_METHOD(0x37, lstore            );
DEFINE_INS_HELPER_METHOD(0x38, fstore            );
DEFINE_INS_HELPER_METHOD(0x39, dstore            );
DEFINE_INS_HELPER_METHOD(0x3a, astore            );
DEFINE_INS_HELPER_METHOD(0x3b, istore_0          );
DEFINE_INS_HELPER_METHOD(0x3c, istore_1          );
DEFINE_INS_HELPER_METHOD(0x3d, istore_2          );
DEFINE_INS_HELPER_METHOD(0x3e, istore_3          );
DEFINE_INS_HELPER_METHOD(0x3f, lstore_0          );
DEFINE_INS_HELPER_METHOD(0x40, lstore_1          );
DEFINE_INS_HELPER_METHOD(0x41, lstore_2          );
DEFINE_INS_HELPER_METHOD(0x42, lstore_3          );
DEFINE_INS_HELPER_METHOD(0x43, fstore_0          );
DEFINE_INS_HELPER_METHOD(0x44, fstore_1          );
DEFINE_INS_HELPER_METHOD(0x45, fstore_2          );
DEFINE_INS_HELPER_METHOD(0x46, fstore_3          );
DEFINE_INS_HELPER_METHOD(0x47, dstore_0          );
DEFINE_INS_HELPER_METHOD(0x48, dstore_1          );
DEFINE_INS_HELPER_METHOD(0x49, dstore_2          );
DEFINE_INS_HELPER_METHOD(0x4a, dstore_3          );
DEFINE_INS_HELPER_METHOD(0x4b, astore_0          );
DEFINE_INS_HELPER_METHOD(0x4c, astore_1          );
DEFINE_INS_HELPER_METHOD(0x4d, astore_2          );
DEFINE_INS_HELPER_METHOD(0x4e, astore_3          );
DEFINE_INS_HELPER_METHOD(0x4f, iastore           );
DEFINE_INS_HELPER_METHOD(0x50, lastore           );
DEFINE_INS_HELPER_METHOD(0x51, fastore           );
DEFINE_INS_HELPER_METHOD(0x52, dastore           );
DEFINE_INS_HELPER_METHOD(0x53, aastore           );
DEFINE_INS_HELPER_METHOD(0x54, bastore           );
DEFINE_INS_HELPER_METHOD(0x55, castore           );
DEFINE_INS_HELPER_METHOD(0x56, sastore           );
DEFINE_INS_HELPER_METHOD(0x57, pop               );
DEFINE_INS_HELPER_METHOD(0x58, pop2              );
DEFINE_INS_HELPER_METHOD(0x59, dup               );
DEFINE_INS_HELPER_METHOD(0x5a, dup_x1            );
DEFINE_INS_HELPER_METHOD(0x5b, dup_x2            );
DEFINE_INS_HELPER_METHOD(0x5c, dup2              );
DEFINE_INS_HELPER_METHOD(0x5d, dup2_x1           );
DEFINE_INS_HELPER_METHOD(0x5e, dup2_x2           );
DEFINE_INS_HELPER_METHOD(0x5f, swap              );
DEFINE_INS_HELPER_METHOD(0x60, iadd              );
DEFINE_INS_HELPER_METHOD(0x61, ladd              );
DEFINE_INS_HELPER_METHOD(0x62, fadd              );
DEFINE_INS_HELPER_METHOD(0x63, dadd              );
DEFINE_INS_HELPER_METHOD(0x64, isub              );
DEFINE_INS_HELPER_METHOD(0x65, lsub              );
DEFINE_INS_HELPER_METHOD(0x66, fsub              );
DEFINE_INS_HELPER_METHOD(0x67, dsub              );
DEFINE_INS_HELPER_METHOD(0x68, imul              );
DEFINE_INS_HELPER_METHOD(0x69, lmul              );
DEFINE_INS_HELPER_METHOD(0x6a, fmul              );
DEFINE_INS_HELPER_METHOD(0x6b, dmul              );
DEFINE_INS_HELPER_METHOD(0x6c, idiv              );
DEFINE_INS_HELPER_METHOD(0x6d, ldiv              );
DEFINE_INS_HELPER_METHOD(0x6e, fdiv              );
DEFINE_INS_HELPER_METHOD(0x6f, ddiv              );
DEFINE_INS_HELPER_METHOD(0x70, irem              );
DEFINE_INS_HELPER_METHOD(0x71, lrem              );
DEFINE_INS_HELPER_METHOD(0x72, frem              );
DEFINE_INS_HELPER_METHOD(0x73, drem              );
DEFINE_INS_HELPER_METHOD(0x74, ine               );
DEFINE_INS_HELPER_METHOD(0x75, lne               );
DEFINE_INS_HELPER_METHOD(0x76, fne               );
DEFINE_INS_HELPER_METHOD(0x77, dne               );
DEFINE_INS_HELPER_METHOD(0x78, ishl              );
DEFINE_INS_HELPER_METHOD(0x79, lshl              );
DEFINE_INS_HELPER_METHOD(0x7a, ishr              );
DEFINE_INS_HELPER_METHOD(0x7b, lshr              );
DEFINE_INS_HELPER_METHOD(0x7c, iushr             );
DEFINE_INS_HELPER_METHOD(0x7d, lushr             );
DEFINE_INS_HELPER_METHOD(0x7e, iand              );
DEFINE_INS_HELPER_METHOD(0x7f, land              );
DEFINE_INS_HELPER_METHOD(0x80, ior               );
DEFINE_INS_HELPER_METHOD(0x81, lor               );
DEFINE_INS_HELPER_METHOD(0x82, ixor              );
DEFINE_INS_HELPER_METHOD(0x83, lxor              );
DEFINE_INS_HELPER_METHOD(0x84, iinc              );
DEFINE_INS_HELPER_METHOD(0x85, i2l               );
DEFINE_INS_HELPER_METHOD(0x86, i2f               );
DEFINE_INS_HELPER_METHOD(0x87, i2d               );
DEFINE_INS_HELPER_METHOD(0x88, l2i               );
DEFINE_INS_HELPER_METHOD(0x89, l2f               );
DEFINE_INS_HELPER_METHOD(0x8a, l2d               );
DEFINE_INS_HELPER_METHOD(0x8b, f2i               );
DEFINE_INS_HELPER_METHOD(0x8c, f2l               );
DEFINE_INS_HELPER_METHOD(0x8d, f2d               );
DEFINE_INS_HELPER_METHOD(0x8e, d2i               );
DEFINE_INS_HELPER_METHOD(0x8f, d2l               );
DEFINE_INS_HELPER_METHOD(0x90, d2f               );
DEFINE_INS_HELPER_METHOD(0x91, i2b               );
DEFINE_INS_HELPER_METHOD(0x92, i2c               );
DEFINE_INS_HELPER_METHOD(0x93, i2s               );
DEFINE_INS_HELPER_METHOD(0x94, lcmp              );
DEFINE_INS_HELPER_METHOD(0x95, fcmpl             );
DEFINE_INS_HELPER_METHOD(0x96, fcmp              );
DEFINE_INS_HELPER_METHOD(0x97, dcmpl             );
DEFINE_INS_HELPER_METHOD(0x98, dcmp              );
DEFINE_INS_HELPER_METHOD(0x99, ifeq              );
DEFINE_INS_HELPER_METHOD(0x9a, ifne              );
DEFINE_INS_HELPER_METHOD(0x9b, iflt              );
DEFINE_INS_HELPER_METHOD(0x9c, ife               );
DEFINE_INS_HELPER_METHOD(0x9d, ift               );
DEFINE_INS_HELPER_METHOD(0x9e, ifle              );
DEFINE_INS_HELPER_METHOD(0x9f, if_icmpeq         );
DEFINE_INS_HELPER_METHOD(0xa0, if_icmpne         );
DEFINE_INS_HELPER_METHOD(0xa1, if_icmplt         );
DEFINE_INS_HELPER_METHOD(0xa2, if_icmpe          );
DEFINE_INS_HELPER_METHOD(0xa3, if_icmpt          );
DEFINE_INS_HELPER_METHOD(0xa4, if_icmple         );
DEFINE_INS_HELPER_METHOD(0xa5, if_acmpeq         );
DEFINE_INS_HELPER_METHOD(0xa6, if_acmpne         );
DEFINE_INS_HELPER_METHOD(0xa7, gotojump          );
DEFINE_INS_HELPER_METHOD(0xa8, jsr               );
DEFINE_INS_HELPER_METHOD(0xa9, ret               );
DEFINE_INS_HELPER_METHOD(0xaa, tableswitch       );
DEFINE_INS_HELPER_METHOD(0xab, lookupswitch      );
DEFINE_INS_HELPER_METHOD(0xac, ireturn           );
DEFINE_INS_HELPER_METHOD(0xad, lreturn           );
DEFINE_INS_HELPER_METHOD(0xae, freturn           );
DEFINE_INS_HELPER_METHOD(0xaf, dreturn           );
DEFINE_INS_HELPER_METHOD(0xb0, areturn           );
DEFINE_INS_HELPER_METHOD(0xb1, voidreturn        );
DEFINE_INS_HELPER_METHOD(0xb2, getstatic         );
DEFINE_INS_HELPER_METHOD(0xb3, putstatic         );
DEFINE_INS_HELPER_METHOD(0xb4, getfield          );
DEFINE_INS_HELPER_METHOD(0xb5, putfield          );
DEFINE_INS_HELPER_METHOD(0xb6, invokevirtual     );
DEFINE_INS_HELPER_METHOD(0xb7, invokespecial     );
DEFINE_INS_HELPER_METHOD(0xb8, invokestatic      );
DEFINE_INS_HELPER_METHOD(0xb9, invokeinterface   );
DEFINE_INS_HELPER_METHOD(0xba, invokedynamic     );
DEFINE_INS_HELPER_METHOD(0xbb, newobj            );
DEFINE_INS_HELPER_METHOD(0xbc, newarray          );
DEFINE_INS_HELPER_METHOD(0xbd, anewarray         );
DEFINE_INS_HELPER_METHOD(0xbe, arraylength       );
DEFINE_INS_HELPER_METHOD(0xbf, athrow            );
DEFINE_INS_HELPER_METHOD(0xc0, checkcast         );
DEFINE_INS_HELPER_METHOD(0xc1, instanceof        );
DEFINE_INS_HELPER_METHOD(0xc2, monitorenter      );
DEFINE_INS_HELPER_METHOD(0xc3, monitorexit       );
DEFINE_INS_HELPER_METHOD(0xc4, wide              );
DEFINE_INS_HELPER_METHOD(0xc5, multianewarray    );
DEFINE_INS_HELPER_METHOD(0xc6, ifnull            );
DEFINE_INS_HELPER_METHOD(0xc7, ifnonnull         );
DEFINE_INS_HELPER_METHOD(0xc8, goto_w            );
DEFINE_INS_HELPER_METHOD(0xc9, jsr_w             );
DEFINE_INS_HELPER_METHOD(0xca, breakpoint        );
DEFINE_INS_HELPER_METHOD(0xfe, impdep1           );
DEFINE_INS_HELPER_METHOD(0xff, leavefinally      );

#define INS_NOP                 0x00
#define INS_ACONST_NULL         0x01
#define INS_ICONST_M1           0x02
#define INS_ICONST_0            0x03
#define INS_ICONST_1            0x04
#define INS_ICONST_2            0x05
#define INS_ICONST_3            0x06
#define INS_ICONST_4            0x07
#define INS_ICONST_5            0x08
#define INS_LCONST_0            0x09
#define INS_LCONST_1            0x0a
#define INS_FCONST_0            0x0b
#define INS_FCONST_1            0x0c
#define INS_FCONST_2            0x0d
#define INS_DCONST_0            0x0e
#define INS_DCONST_1            0x0f
#define INS_BIPUSH              0x10
#define INS_SIPUSH              0x11
#define INS_LDC                 0x12
#define INS_LDC_W               0x13
#define INS_LDC2_W              0x14
#define INS_ILOAD               0x15
#define INS_LLOAD               0x16
#define INS_FLOAD               0x17
#define INS_DLOAD               0x18
#define INS_ALOAD               0x19
#define INS_ILOAD_0             0x1a
#define INS_ILOAD_1             0x1b
#define INS_ILOAD_2             0x1c
#define INS_ILOAD_3             0x1d
#define INS_LLOAD_0             0x1e
#define INS_LLOAD_1             0x1f
#define INS_LLOAD_2             0x20
#define INS_LLOAD_3             0x21
#define INS_FLOAD_0             0x22
#define INS_FLOAD_1             0x23
#define INS_FLOAD_2             0x24
#define INS_FLOAD_3             0x25
#define INS_DLOAD_0             0x26
#define INS_DLOAD_1             0x27
#define INS_DLOAD_2             0x28
#define INS_DLOAD_3             0x29
#define INS_ALOAD_0             0x2a
#define INS_ALOAD_1             0x2b
#define INS_ALOAD_2             0x2c
#define INS_ALOAD_3             0x2d
#define INS_IALOAD              0x2e
#define INS_LALOAD              0x2f
#define INS_FALOAD              0x30
#define INS_DALOAD              0x31
#define INS_AALOAD              0x32
#define INS_BALOAD              0x33
#define INS_CALOAD              0x34
#define INS_SALOAD              0x35
#define INS_ISTORE              0x36
#define INS_LSTORE              0x37
#define INS_FSTORE              0x38
#define INS_DSTORE              0x39
#define INS_ASTORE              0x3a
#define INS_ISTORE_0            0x3b
#define INS_ISTORE_1            0x3c
#define INS_ISTORE_2            0x3d
#define INS_ISTORE_3            0x3e
#define INS_LSTORE_0            0x3f
#define INS_LSTORE_1            0x40
#define INS_LSTORE_2            0x41
#define INS_LSTORE_3            0x42
#define INS_FSTORE_0            0x43
#define INS_FSTORE_1            0x44
#define INS_FSTORE_2            0x45
#define INS_FSTORE_3            0x46
#define INS_DSTORE_0            0x47
#define INS_DSTORE_1            0x48
#define INS_DSTORE_2            0x49
#define INS_DSTORE_3            0x4a
#define INS_ASTORE_0            0x4b
#define INS_ASTORE_1            0x4c
#define INS_ASTORE_2            0x4d
#define INS_ASTORE_3            0x4e
#define INS_IASTORE             0x4f
#define INS_LASTORE             0x50
#define INS_FASTORE             0x51
#define INS_DASTORE             0x52
#define INS_AASTORE             0x53
#define INS_BASTORE             0x54
#define INS_CASTORE             0x55
#define INS_SASTORE             0x56
#define INS_POP                 0x57
#define INS_POP2                0x58
#define INS_DUP                 0x59
#define INS_DUP_X1              0x5a
#define INS_DUP_X2              0x5b
#define INS_DUP2                0x5c
#define INS_DUP2_X1             0x5d
#define INS_DUP2_X2             0x5e
#define INS_SWAP                0x5f
#define INS_IADD                0x60
#define INS_LADD                0x61
#define INS_FADD                0x62
#define INS_DADD                0x63
#define INS_ISUB                0x64
#define INS_LSUB                0x65
#define INS_FSUB                0x66
#define INS_DSUB                0x67
#define INS_IMUL                0x68
#define INS_LMUL                0x69
#define INS_FMUL                0x6a
#define INS_DMUL                0x6b
#define INS_IDIV                0x6c
#define INS_LDIV                0x6d
#define INS_FDIV                0x6e
#define INS_DDIV                0x6f
#define INS_IREM                0x70
#define INS_LREM                0x71
#define INS_FREM                0x72
#define INS_DREM                0x73
#define INS_INEG                0x74
#define INS_LNEG                0x75
#define INS_FNEG                0x76
#define INS_DNEG                0x77
#define INS_ISHL                0x78
#define INS_LSHL                0x79
#define INS_ISHR                0x7a
#define INS_LSHR                0x7b
#define INS_IUSHR               0x7c
#define INS_LUSHR               0x7d
#define INS_IAND                0x7e
#define INS_LAND                0x7f
#define INS_IOR                 0x80
#define INS_LOR                 0x81
#define INS_IXOR                0x82
#define INS_LXOR                0x83
#define INS_IINC                0x84
#define INS_I2L                 0x85
#define INS_I2F                 0x86
#define INS_I2D                 0x87
#define INS_L2I                 0x88
#define INS_L2F                 0x89
#define INS_L2D                 0x8a
#define INS_F2I                 0x8b
#define INS_F2L                 0x8c
#define INS_F2D                 0x8d
#define INS_D2I                 0x8e
#define INS_D2L                 0x8f
#define INS_D2F                 0x90
#define INS_I2B                 0x91
#define INS_I2C                 0x92
#define INS_I2S                 0x93
#define INS_LCMP                0x94
#define INS_FCMPL               0x95
#define INS_FCMPG               0x96
#define INS_DCMPL               0x97
#define INS_DCMPG               0x98
#define INS_IFEQ                0x99
#define INS_IFNE                0x9a
#define INS_IFLT                0x9b
#define INS_IFGE                0x9c
#define INS_IFGT                0x9d
#define INS_IFLE                0x9e
#define INS_IF_ICMPEQ           0x9f
#define INS_IF_ICMPNE           0xa0
#define INS_IF_ICMPLT           0xa1
#define INS_IF_ICMPGE           0xa2
#define INS_IF_ICMPGT           0xa3
#define INS_IF_ICMPLE           0xa4
#define INS_IF_ACMPEQ           0xa5
#define INS_IF_ACMPNE           0xa6
#define INS_GOTO                0xa7
#define INS_JSR                 0xa8
#define INS_RET                 0xa9
#define INS_TABLESWITCH         0xaa
#define INS_LOOKUPSWITCH        0xab
#define INS_IRETURN             0xac
#define INS_LRETURN             0xad
#define INS_FRETURN             0xae
#define INS_DRETURN             0xaf
#define INS_ARETURN             0xb0
#define INS_RETURN              0xb1
#define INS_GETSTATIC           0xb2
#define INS_PUTSTATIC           0xb3
#define INS_GETFIELD            0xb4
#define INS_PUTFIELD            0xb5
#define INS_INVOKEVIRTUAL       0xb6
#define INS_INVOKESPECIAL       0xb7
#define INS_INVOKESTATIC        0xb8
#define INS_INVOKEINTERFACE     0xb9
#define INS_INVOKEDYNAMIC       0xba
#define INS_NEW                 0xbb
#define INS_NEWARRAY            0xbc
#define INS_ANEWARRAY           0xbd
#define INS_ARRAYLENGTH         0xbe
#define INS_ATHROW              0xbf
#define INS_CHECKCAST           0xc0
#define INS_INSTANCEOF          0xc1
#define INS_MONITORENTER        0xc2
#define INS_MONITOREXIT         0xc3
#define INS_WIDE                0xc4
#define INS_MULTIANEWARRAY      0xc5
#define INS_IFNULL              0xc6
#define INS_IFNONNULL           0xc7
#define INS_GOTO_W              0xc8
#define INS_JSR_W               0xc9
#endif //GARLIC_JVM_INS_HELPER_H
