#ifndef GARLIC_JD_API_MATCHER_H
#define GARLIC_JD_API_MATCHER_H

typedef enum jd_graph_api_category {
    JD_API_CAT_UNKNOWN = 0,
    JD_API_CAT_PRIVACY,
    JD_API_CAT_DEVICE,
    JD_API_CAT_NETWORK,
    JD_API_CAT_FILE,
    JD_API_CAT_CRYPTO,
    JD_API_CAT_DYNAMIC,
    JD_API_CAT_PROCESS,
    JD_API_CAT_WEBVIEW,
} jd_graph_api_category;

typedef enum jd_graph_api_type {
    JD_GRAPH_NODE_API_UNKNOWN = 0,
    JD_GRAPH_NODE_CLIPBOARD,
    JD_GRAPH_NODE_CAMERA,
    JD_GRAPH_NODE_MICROPHONE,
    JD_GRAPH_NODE_SCREENSHOT,
    JD_GRAPH_NODE_SCREEN_RECORD,
    JD_GRAPH_NODE_ACCESSIBILITY,
    JD_GRAPH_NODE_NOTIFICATION_LISTENER,
    JD_GRAPH_NODE_GET_ANDROID_ID,
    JD_GRAPH_NODE_GET_DEVICE_ID,
    JD_GRAPH_NODE_GET_IMEI,
    JD_GRAPH_NODE_GET_MEID,
    JD_GRAPH_NODE_GET_IMSI,
    JD_GRAPH_NODE_GET_ICCID,
    JD_GRAPH_NODE_GET_SERIAL,
    JD_GRAPH_NODE_GET_MAC_ADDRESS,
    JD_GRAPH_NODE_GET_BSSID,
    JD_GRAPH_NODE_GET_SSID,
    JD_GRAPH_NODE_GET_SIM_INFO,
    JD_GRAPH_NODE_GET_NETWORK_INFO,
    JD_GRAPH_NODE_GET_WIFI_INFO,
    JD_GRAPH_NODE_GET_SENSOR_LIST,
    JD_GRAPH_NODE_GET_LOCATION,
    JD_GRAPH_NODE_GET_CONTACTS,
    JD_GRAPH_NODE_GET_SMS,
    JD_GRAPH_NODE_GET_CALL_LOG,
    JD_GRAPH_NODE_GET_ACCOUNTS,
    JD_GRAPH_NODE_GET_INSTALLED_APPS,
    JD_GRAPH_NODE_FILE_OPEN,
    JD_GRAPH_NODE_FILE_READ,
    JD_GRAPH_NODE_FILE_WRITE,
    JD_GRAPH_NODE_FILE_DELETE,
    JD_GRAPH_NODE_NET_URL_INIT,
    JD_GRAPH_NODE_NET_OPEN_CONNECTION,
    JD_GRAPH_NODE_NET_CONNECT,
    JD_GRAPH_NODE_NET_EXECUTE,
    JD_GRAPH_NODE_NET_SEND,
    JD_GRAPH_NODE_NET_RECEIVE,
    JD_GRAPH_NODE_NET_DNS_QUERY,
    JD_GRAPH_NODE_NET_TLS_HANDSHAKE,
    JD_GRAPH_NODE_AES_ENCRYPT,
    JD_GRAPH_NODE_AES_DECRYPT,
    JD_GRAPH_NODE_RSA_ENCRYPT,
    JD_GRAPH_NODE_RSA_DECRYPT,
    JD_GRAPH_NODE_HASH_MD5,
    JD_GRAPH_NODE_HASH_SHA1,
    JD_GRAPH_NODE_HASH_SHA256,
    JD_GRAPH_NODE_BASE64_ENCODE,
    JD_GRAPH_NODE_BASE64_DECODE,
    JD_GRAPH_NODE_LOAD_DEX,
    JD_GRAPH_NODE_LOAD_SO,
    JD_GRAPH_NODE_JNI_CALL,
    JD_GRAPH_NODE_REFLECTION,
    JD_GRAPH_NODE_EXEC_CMD,
    JD_GRAPH_NODE_FORK_PROCESS,
    JD_GRAPH_NODE_SHELL,
    JD_GRAPH_NODE_WEBVIEW_LOAD_URL,
    JD_GRAPH_NODE_WEBVIEW_EVAL_JS,
    JD_GRAPH_NODE_GET_SYSTEM_PROPERTY,
    JD_GRAPH_NODE_ANTI_DEBUG,
    JD_GRAPH_NODE_DYNAMIC_RECEIVER,
    JD_GRAPH_NODE_START_ACTIVITY,
    JD_GRAPH_NODE_PERSISTENCE,
    JD_GRAPH_NODE_OVERLAY_ATTACK,
    JD_GRAPH_NODE_BINDER_TRANSACT,
    JD_GRAPH_NODE_ACCESSIBILITY_EXPL,
    JD_GRAPH_NODE_KEYLOGGING,
    JD_GRAPH_NODE_HIDE_ICON,
    JD_GRAPH_NODE_DEVICE_ADMIN,
    JD_GRAPH_NODE_PROVIDER_EXPOSE,
    JD_GRAPH_NODE_SEND_BROADCAST,
    JD_GRAPH_NODE_START_SERVICE,
    JD_GRAPH_NODE_BIOMETRIC_BYPASS,
    JD_GRAPH_NODE_SCREEN_LOCK,
    JD_GRAPH_NODE_INTENT_REDIRECT,
    JD_GRAPH_NODE_CRYPTO,
} jd_graph_api_type;

typedef struct {
    const char *clazz;
    const char *method;
    const char *desc;
    jd_graph_api_type behavior;
} jd_api_matcher;

static jd_api_matcher api_table[] = {
        {
                "Landroid/content/ClipboardManager;",
                "getPrimaryClip",
                "()Landroid/content/ClipData;",
                JD_GRAPH_NODE_CLIPBOARD
        },
        {
                "Landroid/content/ClipboardManager;",
                "setText",
                "(Ljava/lang/CharSequence;)V",
                JD_GRAPH_NODE_CLIPBOARD
        },
        {
                "Landroid/content/ClipboardManager;",
                "addPrimaryClipChangedListener",
                "(Landroid/content/ClipboardManager$OnPrimaryClipChangedListener;)V",
                JD_GRAPH_NODE_CLIPBOARD
        },
        {
                "Landroid/hardware/Camera;",
                "open",
                "()Landroid/hardware/Camera;",
                JD_GRAPH_NODE_CAMERA
        },
        {
                "Landroid/hardware/camera2/CameraManager;",
                "openCamera",
                "(Ljava/lang/String;Landroid/hardware/camera2/CameraDevice$StateCallback;Landroid/os/Handler;)V",
                JD_GRAPH_NODE_CAMERA
        },
        {
                "Landroid/hardware/camera2/CameraManager;",
                "registerAvailabilityCallback",
                "(Landroid/hardware/camera2/CameraManager$AvailabilityCallback;Landroid/os/Handler;)V",
                JD_GRAPH_NODE_CAMERA
        },
        {
                "Landroid/media/MediaRecorder;",
                "setAudioSource",
                "(I)V",
                JD_GRAPH_NODE_MICROPHONE
        },
        {
                "Landroid/media/AudioRecord;",
                "startRecording",
                "()V",
                JD_GRAPH_NODE_MICROPHONE
        },
        {
                "Landroid/media/MediaPlayer;",
                "setAudioStreamType",
                "(I)V",
                JD_GRAPH_NODE_MICROPHONE
        },
        {
                "Landroid/media/AudioRecord;",
                "registerAudioRecordCallback",
                "(Landroid/media/AudioRecord$AudioRecordCallback;Ljava/util/concurrent/Executor;)V",
                JD_GRAPH_NODE_MICROPHONE
        },
        {
                "Landroid/media/AudioPlaybackCaptureConfiguration$Builder;",
                "addMatchingUid",
                "(I)Landroid/media/AudioPlaybackCaptureConfiguration$Builder;",
                JD_GRAPH_NODE_MICROPHONE
        },
        {
                "Landroid/media/projection/MediaProjectionManager;",
                "getMediaProjection",
                "(ILandroid/content/Intent;)Landroid/media/projection/MediaProjection;",
                JD_GRAPH_NODE_SCREEN_RECORD
        },
        {
                "Landroid/media/projection/MediaProjection;",
                "createVirtualDisplay",
                "(Ljava/lang/String;IIIIILandroid/view/Surface;Landroid/hardware/display/VirtualDisplay$Callback;Landroid/os/Handler;)Landroid/hardware/display/VirtualDisplay;",
                JD_GRAPH_NODE_SCREEN_RECORD
        },
        {
                "Landroid/media/ImageReader;",
                "newInstance",
                "(IIII)Landroid/media/ImageReader;",
                JD_GRAPH_NODE_SCREEN_RECORD
        },
        {
                "Landroid/media/ImageReader;",
                "setOnImageAvailableListener",
                "(Landroid/media/ImageReader$OnImageAvailableListener;Landroid/os/Handler;)V",
                JD_GRAPH_NODE_SCREEN_RECORD
        },
        {
                "Landroid/app/DownloadManager$Request;",
                "setNotificationVisibility",
                "(I)Landroid/app/DownloadManager$Request;",
                JD_GRAPH_NODE_SCREEN_RECORD
        },
        {
                "Landroid/view/Window;",
                "takeSurface",
                "(Landroid/view/SurfaceHolder$Callback2;)V",
                JD_GRAPH_NODE_SCREENSHOT
        },
        {
                "Landroid/accessibilityservice/AccessibilityService;",
                "getServiceInfo",
                "()Landroid/accessibilityservice/AccessibilityServiceInfo;",
                JD_GRAPH_NODE_ACCESSIBILITY
        },
        {
                "Landroid/service/notification/NotificationListenerService;",
                "getActiveNotifications",
                "()[Landroid/service/notification/StatusBarNotification;",
                JD_GRAPH_NODE_NOTIFICATION_LISTENER
        },
        
        {
                "Landroid/telephony/TelephonyManager;",
                "getDeviceId",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_DEVICE_ID
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "getDeviceId",
                "(I)Ljava/lang/String;",
                JD_GRAPH_NODE_GET_DEVICE_ID
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "getImei",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_IMEI
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "getMeid",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_MEID
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "getSubscriberId",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_IMSI
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "getSimSerialNumber",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_ICCID
        },
        {
                "Landroid/os/Build;",
                "getSerial",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_SERIAL
        },
        {
                "Landroid/os/Build;",
                "getFingerprint",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_SERIAL
        },
        {
                "Landroid/net/wifi/WifiInfo;",
                "getMacAddress",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_MAC_ADDRESS
        },
        {
                "Landroid/net/wifi/WifiInfo;",
                "getBSSID",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_BSSID
        },
        {
                "Landroid/net/wifi/WifiInfo;",
                "getSSID",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_SSID
        },
        {
                "Landroid/telephony/SubscriptionManager;",
                "getActiveSubscriptionInfoList",
                "()Ljava/util/List;",
                JD_GRAPH_NODE_GET_SIM_INFO
        },
        {
                "Landroid/net/ConnectivityManager;",
                "getActiveNetworkInfo",
                "()Landroid/net/NetworkInfo;",
                JD_GRAPH_NODE_GET_NETWORK_INFO
        },
        {
                "Landroid/net/wifi/WifiManager;",
                "getConnectionInfo",
                "()Landroid/net/wifi/WifiInfo;",
                JD_GRAPH_NODE_GET_WIFI_INFO
        },
        {
                "Landroid/hardware/SensorManager;",
                "getSensorList",
                "(I)Ljava/util/List;",
                JD_GRAPH_NODE_GET_SENSOR_LIST
        },
        {       
                "Landroid/hardware/SensorManager;", 
                "registerListener", 
                "(Landroid/hardware/SensorEventListener;Landroid/hardware/Sensor;I)Z", 
                JD_GRAPH_NODE_GET_SENSOR_LIST 
        },
        {
                "Landroid/hardware/Sensor;",
                "getStringType",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_GET_SENSOR_LIST
        },
        {
                "Landroid/location/LocationManager;",
                "getLastKnownLocation",
                "(Ljava/lang/String;)Landroid/location/Location;",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/location/LocationManager;",
                "requestLocationUpdates",
                "(Ljava/lang/String;JFLandroid/location/LocationListener;)V",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "getAllCellInfo",
                "()Ljava/util/List;",
                JD_GRAPH_NODE_GET_LOCATION 
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "getCellLocation",
                "()Landroid/telephony/CellLocation;",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Lcom/google/android/gms/location/FusedLocationProviderClient;",
                "getLastLocation",
                "()Lcom/google/android/gms/tasks/Task;",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/telephony/CellSignalStrength;",
                "getDbm",
                "()I",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/bluetooth/BluetoothAdapter;",
                "getBondedDevices",
                "()Ljava/util/Set;",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/bluetooth/BluetoothAdapter;",
                "startDiscovery",
                "()Z",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/bluetooth/le/BluetoothLeScanner;",
                "startScan",
                "(Ljava/util/List;Landroid/bluetooth/le/ScanSettings;Landroid/bluetooth/le/ScanCallback;)V",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/location/LocationManager;",
                "getLastKnownLocation",
                "(Ljava/lang/String;)Landroid/location/Location;",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/location/LocationManager;",
                "getCurrentLocation",
                "(Ljava/lang/String;Landroid/location/CancellationSignal;Ljava/util/concurrent/Executor;Ljava/util/function/Consumer;)V",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/location/LocationManager;",
                "requestLocationUpdates",
                "(Ljava/lang/String;JFLandroid/location/LocationListener;)V",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/location/LocationManager;",
                "addProximityAlert",
                "(DDFJLandroid/app/PendingIntent;)V",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/net/wifi/WifiManager;",
                "getConfiguredNetworks",
                "()Ljava/util/List;",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/location/LocationManager;",
                "getCurrentLocation",
                "(Ljava/lang/String;Landroid/location/CancellationSignal;Ljava/util/concurrent/Executor;Ljava/util/function/Consumer;)V",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/location/LocationManager;",
                "addProximityAlert",
                "(DDFJLandroid/app/PendingIntent;)V",
                JD_GRAPH_NODE_GET_LOCATION
        },
        {
                "Landroid/accounts/AccountManager;",
                "getAccounts",
                "()[Landroid/accounts/Account;",
                JD_GRAPH_NODE_GET_ACCOUNTS
        },
        {
                "Landroid/content/pm/PackageManager;",
                "getInstalledPackages",
                "(I)Ljava/util/List;",
                JD_GRAPH_NODE_GET_INSTALLED_APPS
        },
        {
                "Landroid/content/pm/PackageManager;",
                "getInstalledApplications",
                "(I)Ljava/util/List;",
                JD_GRAPH_NODE_GET_INSTALLED_APPS
        },
        {
                "Landroid/content/pm/PackageManager;",
                "getPackageInfo",
                "(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;",
                JD_GRAPH_NODE_GET_INSTALLED_APPS
        },
        {
                "Landroid/content/pm/PackageManager;",
                "queryIntentActivities",
                "(Landroid/content/Intent;I)Ljava/util/List;",
                JD_GRAPH_NODE_GET_INSTALLED_APPS
        },
        {
                "Landroid/content/pm/LauncherApps;",
                "getApplicationInfo",
                "(Ljava/lang/String;ILandroid/os/UserHandle;)Landroid/content/pm/ApplicationInfo;",
                JD_GRAPH_NODE_GET_INSTALLED_APPS
        },
        {
                "Landroid/content/ContentResolver;",
                "query",
                "(Landroid/net/Uri;[Ljava/lang/String;Landroid/os/Bundle;Landroid/os/CancellationSignal;)Landroid/database/Cursor;",
                JD_GRAPH_NODE_GET_SMS
        },
        {
                "Landroid/content/ContentResolver;",
                "query",
                "(Landroid/net/Uri;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;",
                JD_GRAPH_NODE_GET_SMS
        },
        
        {
                "Ljava/io/File;",
                "<init>",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Ljava/io/RandomAccessFile;",
                "<init>",
                "(Ljava/lang/String;Ljava/lang/String;)V",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Ljava/io/FileReader;",
                "<init>",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Landroid/os/ParcelFileDescriptor;",
                "fromFd",
                "(I)Landroid/os/ParcelFileDescriptor;",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Landroid/os/MemoryFile;",
                "<init>",
                "(Ljava/lang/String;I)V",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Landroid/os/ParcelFileDescriptor;",
                "dup",
                "()Landroid/os/ParcelFileDescriptor;",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Landroid/os/SharedMemory;",
                "create",
                "(Ljava/lang/String;I)Landroid/os/SharedMemory;",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Landroid/os/ParcelFileDescriptor;",
                "detachFd",
                "()I",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Landroid/os/SharedMemory;",
                "create",
                "(Ljava/lang/String;I)Landroid/os/SharedMemory;",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Ljava/nio/file/Files;",
                "readAttributes",
                "(Ljava/nio/file/Path;Ljava/lang/Class;[Ljava/nio/file/LinkOption;)Ljava/nio/file/attribute/BasicFileAttributes;",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Landroid/content/Context;",
                "getSharedPreferences",
                "(Ljava/lang/String;I)Landroid/content/SharedPreferences;",
                JD_GRAPH_NODE_FILE_OPEN
        },
        {
                "Landroid/content/Context;",
                "openFileInput",
                "(Ljava/lang/String;)Ljava/io/FileInputStream;",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Ljava/io/FileInputStream;",
                "<init>",
                "(Ljava/io/File;)V",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Landroid/content/res/AssetManager;",
                "open",
                "(Ljava/lang/String;)Ljava/io/InputStream;",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Ljava/io/FileInputStream;",
                "read",
                "([B)I",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Ljava/io/BufferedReader;",
                "readLine",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Ljava/nio/channels/FileChannel;",
                "map",
                "(Ljava/nio/channels/FileChannel$MapMode;JJ)Ljava/nio/channels/MappedByteBuffer;",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Ljava/io/ObjectInputStream;",
                "readObject",
                "()Ljava/lang/Object;",
                JD_GRAPH_NODE_FILE_READ 
        },
        {
                "Landroid/nfc/NfcAdapter;",
                "enableReaderMode",
                "(Landroid/app/Activity;Landroid/nfc/NfcAdapter$ReaderCallback;ILandroid/os/Bundle;)V",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Landroid/nfc/NdefRecord;",
                "getPayload",
                "()[B",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Landroid/nfc/NfcAdapter;",
                "enableReaderMode",
                "(Landroid/app/Activity;Landroid/nfc/NfcAdapter$ReaderCallback;ILandroid/os/Bundle;)V",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Landroid/nfc/NdefRecord;",
                "getPayload",
                "()[B",
                JD_GRAPH_NODE_FILE_READ
        },
        {
                "Landroid/content/Context;",
                "openFileOutput",
                "(Ljava/lang/String;I)Ljava/io/FileOutputStream;",
                JD_GRAPH_NODE_FILE_WRITE
        },
        {
                "Ljava/io/FileOutputStream;",
                "<init>",
                "(Ljava/io/File;)V",
                JD_GRAPH_NODE_FILE_WRITE
        },
        {
                "Ljava/io/RandomAccessFile;",
                "write",
                "([B)V",
                JD_GRAPH_NODE_FILE_WRITE
        },
        {
                "Ljava/io/FileOutputStream;",
                "write",
                "([B)V",
                JD_GRAPH_NODE_FILE_WRITE
        },
        {
                "Ljava/io/BufferedWriter;",
                "write",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_FILE_WRITE
        },
        {
                "Landroid/content/ContentResolver;",
                "insert",
                "(Landroid/net/Uri;Landroid/content/ContentValues;)Landroid/net/Uri;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Ljava/io/ObjectOutputStream;",
                "writeObject",
                "(Ljava/lang/Object;)V",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/os/SharedMemory;",
                "mapReadWrite",
                "()Ljava/nio/ByteBuffer;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/os/SharedMemory;",
                "mapReadWrite",
                "()Ljava/nio/ByteBuffer;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Ljava/nio/file/Files;",
                "createSymbolicLink",
                "(Ljava/nio/file/Path;Ljava/nio/file/Path;[Ljava/nio/file/attribute/FileAttribute;)Ljava/nio/file/Path;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Ljava/nio/file/Files;",
                "setPosixFilePermissions",
                "(Ljava/nio/file/Path;Ljava/util/Set;)Ljava/nio/file/Path;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/hardware/usb/UsbRequest;",
                "queue",
                "(Ljava/nio/ByteBuffer;I)Z",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/preference/PreferenceManager;",
                "getDefaultSharedPreferences",
                "(Landroid/content/Context;)Landroid/content/SharedPreferences;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/content/SharedPreferences$Editor;",
                "putString", 
                "(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/content/SharedPreferences$Editor;",
                "commit",
                "()Z", 
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/webkit/CookieManager;",
                "getCookie",
                "(Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/webkit/CookieManager;",
                "setCookie",
                "(Ljava/lang/String;Ljava/lang/String;)V",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/webkit/CookieManager;",
                "removeAllCookies",
                "(Landroid/webkit/ValueCallback;)V",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/app/backup/BackupManager;",
                "dataChanged",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/app/backup/BackupAgent;",
                "onBackup",
                "(Landroid/os/ParcelFileDescriptor;Landroid/app/backup/BackupDataOutput;Landroid/os/ParcelFileDescriptor;)V",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/app/backup/BackupAgentHelper;",
                "addHelper",
                "(Ljava/lang/String;Landroid/app/backup/BackupHelper;)V",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/app/usage/StorageStatsManager;",
                "queryStatsForUid",
                "(Ljava/util/UUID;I)Landroid/app/usage/StorageStats;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/app/usage/StorageStatsManager;",
                "queryStatsForPackage",
                "(Ljava/util/UUID;Ljava/lang/String;Landroid/os/UserHandle;)Landroid/app/usage/StorageStats;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Landroid/drm/DrmManagerClient;",
                "acquireDecryptedObject",
                "(I)Landroid/drm/DrmConvertedStatus;",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Ljavax/net/ssl/KeyManagerFactory;",
                "init",
                "(Ljava/security/KeyStore;[C)V",
                JD_GRAPH_NODE_FILE_WRITE 
        },
        {
                "Ljava/io/File;",
                "delete",
                "()Z",
                JD_GRAPH_NODE_FILE_DELETE
        },
        {
                "Landroid/content/ContentResolver;",
                "delete",
                "(Landroid/net/Uri;Ljava/lang/String;[Ljava/lang/String;)I",
                JD_GRAPH_NODE_FILE_DELETE 
        },
        {
                "Ljava/security/KeyStore;",
                "deleteEntry",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_FILE_DELETE 
        },
        {
                "Ljava/security/KeyStore;",
                "deleteEntry",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_FILE_DELETE 
        },
        
        {
                "Ljava/net/URL;",
                "<init>",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_NET_URL_INIT
        },
        {
                "Lokhttp3/Request$Builder;",
                "url",
                "(Ljava/lang/String;)Lokhttp3/Request$Builder;",
                JD_GRAPH_NODE_NET_URL_INIT
        },
        {
                "Ljava/net/URL;",
                "openConnection",
                "()Ljava/net/URLConnection;",
                JD_GRAPH_NODE_NET_OPEN_CONNECTION
        },
        {
                "Ljava/net/URL;",
                "openConnection",
                "(Ljava/net/Proxy;)Ljava/net/URLConnection;",
                JD_GRAPH_NODE_NET_OPEN_CONNECTION
        },
        {
                "Ljava/net/URLConnection;",
                "connect",
                "()V",
                JD_GRAPH_NODE_NET_CONNECT
        },
        {
                "Ljava/net/HttpURLConnection;",
                "connect",
                "()V",
                JD_GRAPH_NODE_NET_CONNECT
        },
        {
                "Ljava/net/Socket;",
                "connect",
                "(Ljava/net/SocketAddress;)V",
                JD_GRAPH_NODE_NET_CONNECT
        },
        {
                "Ljava/net/Socket;",
                "connect",
                "(Ljava/net/SocketAddress;I)V",
                JD_GRAPH_NODE_NET_CONNECT
        },
        {
                "Ljava/net/ServerSocket;",
                "<init>",
                "(I)V",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Ljava/net/ServerSocket;",
                "accept",
                "()Ljava/net/Socket;",
                JD_GRAPH_NODE_NET_CONNECT
        },
        {
                "Landroid/net/LocalSocket;",
                "connect",
                "(Landroid/net/LocalSocketAddress;)V",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/net/VpnService;",
                "prepare",
                "(Landroid/content/Context;)Landroid/content/Intent;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/net/Network;",
                "bindSocket",
                "(Ljava/net/Socket;)V",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/os/ParcelFileDescriptor;",
                "createSocketPair",
                "()[Landroid/os/ParcelFileDescriptor;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/bluetooth/BluetoothDevice;",
                "createRfcommSocketToServiceRecord",
                "(Ljava/util/UUID;)Landroid/bluetooth/BluetoothSocket;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/bluetooth/BluetoothSocket;",
                "connect",
                "()V",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Ljava/nio/channels/Pipe;",
                "open",
                "()Ljava/nio/channels/Pipe;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Ljavax/net/ssl/X509TrustManager;",
                "checkServerTrusted",
                "([Ljava/security/cert/X509Certificate;Ljava/lang/String;)V",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Ljavax/net/ssl/SSLContext;",
                "init",
                "([Ljavax/net/ssl/KeyManager;[Ljavax/net/ssl/TrustManager;Ljava/security/SecureRandom;)V",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Ljavax/net/ssl/HttpsURLConnection;",
                "setDefaultHostnameVerifier",
                "(Ljavax/net/ssl/HostnameVerifier;)V",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/net/VpnService;",
                "prepare",
                "(Landroid/content/Context;)Landroid/content/Intent;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/net/VpnService$Builder;",
                "establish",
                "()Landroid/os/ParcelFileDescriptor;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/net/VpnService$Builder;",
                "addAddress",
                "(Ljava/net/InetAddress;I)Landroid/net/VpnService$Builder;", 
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/app/DownloadManager;",
                "enqueue",
                "(Landroid/app/DownloadManager$Request;)J",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/app/DownloadManager$Request;",
                "setAllowedNetworkTypes",
                "(I)Landroid/app/DownloadManager$Request;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/app/usage/NetworkStatsManager;",
                "queryDetailsForUid",
                "(ILjava/lang/String;JJ)Landroid/app/usage/NetworkStats;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/app/usage/NetworkStatsManager;",
                "querySummary",
                "(ILjava/lang/String;JJ)Landroid/app/usage/NetworkStats;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Landroid/app/usage/NetworkStats$Bucket;",
                "getRxBytes", 
                "()J",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Ljavax/net/ssl/X509KeyManager;",
                "chooseClientAlias",
                "([Ljava/lang/String;[Ljava/security/Principal;Ljava/net/Socket;)Ljava/lang/String;",
                JD_GRAPH_NODE_NET_CONNECT 
        },
        {
                "Lokhttp3/Call;",
                "execute",
                "()Lokhttp3/Response;",
                JD_GRAPH_NODE_NET_EXECUTE
        },
        {
                "Lokhttp3/Call;",
                "enqueue",
                "(Lokhttp3/Callback;)V",
                JD_GRAPH_NODE_NET_EXECUTE
        },
        {
                "Lorg/apache/http/impl/client/DefaultHttpClient;",
                "execute",
                "(Lorg/apache/http/client/methods/HttpUriRequest;)Lorg/apache/http/HttpResponse;",
                JD_GRAPH_NODE_NET_EXECUTE
        },
        {
                "Lokhttp3/OkHttpClient;",
                "newCall",
                "(Lokhttp3/Request;)Lokhttp3/Call;",
                JD_GRAPH_NODE_NET_EXECUTE
        },
        {
                "Ljava/net/DatagramSocket;",
                "send",
                "(Ljava/net/DatagramPacket;)V",
                JD_GRAPH_NODE_NET_SEND
        },
        {
                "Lokhttp3/WebSocket;",
                "send",
                "(Ljava/lang/String;)Z",
                JD_GRAPH_NODE_NET_SEND
        },
        {
                "Lokhttp3/WebSocket;",
                "send",
                "(Lokio/ByteString;)Z",
                JD_GRAPH_NODE_NET_SEND
        },
        {
                "Ljava/io/OutputStream;",
                "write",
                "([B)V",
                JD_GRAPH_NODE_NET_SEND
        },
        {
                "Ljava/net/DatagramSocket;",
                "receive",
                "(Ljava/net/DatagramPacket;)V",
                JD_GRAPH_NODE_NET_RECEIVE
        },
        {
                "Ljava/io/InputStream;",
                "read",
                "([B)I",
                JD_GRAPH_NODE_NET_RECEIVE
        },
        {
                "Ljava/net/InetAddress;",
                "getByName",
                "(Ljava/lang/String;)Ljava/net/InetAddress;",
                JD_GRAPH_NODE_NET_DNS_QUERY
        },
        {
                "Ljava/net/InetAddress;",
                "getAllByName",
                "(Ljava/lang/String;)[Ljava/net/InetAddress;",
                JD_GRAPH_NODE_NET_DNS_QUERY
        },
        {
                "Ljavax/net/ssl/SSLSocket;",
                "startHandshake",
                "()V",
                JD_GRAPH_NODE_NET_TLS_HANDSHAKE
        },
        
        {
                "Ljava/security/MessageDigest;",
                "getInstance",
                "(Ljava/lang/String;)Ljava/security/MessageDigest;",
                JD_GRAPH_NODE_HASH_SHA256 
        },
        {
                "Ljava/security/MessageDigest;",
                "digest",
                "([B)[B",
                JD_GRAPH_NODE_HASH_SHA256
        },
        {
                "Ljava/security/MessageDigest;",
                "digest",
                "()[B",
                JD_GRAPH_NODE_HASH_SHA256
        },
        {
                "Ljavax/crypto/Mac;",
                "getInstance",
                "(Ljava/lang/String;)Ljavax/crypto/Mac;",
                JD_GRAPH_NODE_HASH_SHA256
        },
        {
                "Ljavax/crypto/Mac;",
                "doFinal",
                "([B)[B",
                JD_GRAPH_NODE_HASH_SHA256
        },
        {
                "Ljavax/crypto/Cipher;",
                "getInstance",
                "(Ljava/lang/String;)Ljavax/crypto/Cipher;",
                JD_GRAPH_NODE_AES_ENCRYPT 
        },
        {
                "Ljavax/crypto/Cipher;",
                "init",
                "(ILjava/security/Key;)V",
                JD_GRAPH_NODE_AES_ENCRYPT
        },
        {
                "Ljavax/crypto/Cipher;",
                "init",
                "(ILjava/security/Key;Ljava/security/spec/AlgorithmParameterSpec;)V",
                JD_GRAPH_NODE_AES_ENCRYPT
        },
        {
                "Ljavax/crypto/Cipher;",
                "doFinal",
                "([B)[B",
                JD_GRAPH_NODE_AES_ENCRYPT
        },
        {
                "Ljavax/crypto/Cipher;",
                "doFinal",
                "()[B",
                JD_GRAPH_NODE_AES_ENCRYPT
        },
        {
                "Ljavax/crypto/KeyGenerator;",
                "getInstance",
                "(Ljava/lang/String;)Ljavax/crypto/KeyGenerator;",
                JD_GRAPH_NODE_AES_ENCRYPT 
        },
        {
                "Ljavax/crypto/spec/SecretKeySpec;",
                "<init>",
                "([BLjava/lang/String;)V",
                JD_GRAPH_NODE_AES_ENCRYPT 
        },
        {
                "Ljavax/crypto/spec/IvParameterSpec;",
                "<init>",
                "([B)V",
                JD_GRAPH_NODE_AES_ENCRYPT 
        },
        {
                "Ljava/security/KeyStore;",
                "getInstance",
                "(Ljava/lang/String;)Ljava/security/KeyStore;",
                JD_GRAPH_NODE_AES_ENCRYPT
        },
        {
                "Ljava/security/KeyStore;",
                "load",
                "(Ljava/io/InputStream;[C)V",
                JD_GRAPH_NODE_AES_ENCRYPT
        },
        {
                "Landroid/security/keystore/KeyGenParameterSpec$Builder;",
                "build",
                "()Landroid/security/keystore/KeyGenParameterSpec;",
                JD_GRAPH_NODE_AES_ENCRYPT 
        },
        {
                "Ljava/security/Security;",
                "insertProviderAt",
                "(Ljava/security/Provider;I)I",
                JD_GRAPH_NODE_AES_ENCRYPT 
        },
        {
                "Ljava/security/Signature;",
                "getInstance",
                "(Ljava/lang/String;)Ljava/security/Signature;",
                JD_GRAPH_NODE_RSA_ENCRYPT 
        },
        {
                "Ljava/security/Signature;",
                "sign",
                "()[B",
                JD_GRAPH_NODE_RSA_ENCRYPT
        },
        {
                "Ljava/security/KeyPairGenerator;",
                "getInstance",
                "(Ljava/lang/String;)Ljava/security/KeyPairGenerator;",
                JD_GRAPH_NODE_RSA_ENCRYPT 
        },
        {
                "Ljava/security/Signature;",
                "verify",
                "([B)Z",
                JD_GRAPH_NODE_RSA_DECRYPT
        },
        {
                "Landroid/util/Base64;",
                "encode",
                "([BI)[B",
                JD_GRAPH_NODE_BASE64_ENCODE
        },
        {
                "Landroid/util/Base64;",
                "encodeToString",
                "([BI)Ljava/lang/String;",
                JD_GRAPH_NODE_BASE64_ENCODE
        },
        {
                "Landroid/util/Base64;",
                "decode",
                "(Ljava/lang/String;I)[B",
                JD_GRAPH_NODE_BASE64_DECODE
        },
        {
                "Landroid/util/Base64;",
                "decode",
                "([BI)[B",
                JD_GRAPH_NODE_BASE64_DECODE
        },
        {
                "Ljavax/net/ssl/TrustManagerFactory;",
                "init",
                "(Ljava/security/KeyStore;)V",
                JD_GRAPH_NODE_CRYPTO 
        },
        {
                "Ljava/security/cert/CertificateFactory;",
                "generateCertificates",
                "(Ljava/io/InputStream;)Ljava/util/Collection;",
                JD_GRAPH_NODE_CRYPTO 
        },
        
        {
                "Ldalvik/system/DexClassLoader;",
                "<init>",
                "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/ClassLoader;)V",
                JD_GRAPH_NODE_LOAD_DEX
        },
        {
                "Ldalvik/system/PathClassLoader;",
                "<init>",
                "(Ljava/lang/String;Ljava/lang/ClassLoader;)V",
                JD_GRAPH_NODE_LOAD_DEX
        },
        {
                "Lsun/misc/Unsafe;",
                "defineClass",
                "(Ljava/lang/String;[BIILjava/lang/ClassLoader;Ljava/security/ProtectionDomain;)Ljava/lang/Class;",
                JD_GRAPH_NODE_LOAD_DEX
        },
        {
                "Ldalvik/system/InMemoryDexClassLoader;",
                "<init>",
                "(Ljava/nio/ByteBuffer;Ljava/lang/ClassLoader;)V",
                JD_GRAPH_NODE_LOAD_DEX
        },
        {
                "Landroid/content/Context;",
                "startInstrumentation",
                "(Landroid/content/ComponentName;Ljava/lang/String;Landroid/os/Bundle;)Z",
                JD_GRAPH_NODE_LOAD_DEX 
        },
        {
                "Ldalvik/system/BaseDexClassLoader;",
                "findClass",
                "(Ljava/lang/String;)Ljava/lang/Class;",
                JD_GRAPH_NODE_LOAD_DEX
        },
        {
                "Ldalvik/system/VMStack;",
                "getClosestUserClassLoader",
                "()Ljava/lang/ClassLoader;",
                JD_GRAPH_NODE_LOAD_DEX 
        },
        {
                "Ljava/lang/ClassLoader;",
                "defineClass",
                "([BII)Ljava/lang/Class;",
                JD_GRAPH_NODE_LOAD_DEX 
        },
        {
                "Ldalvik/system/DexFile;",
                "defineClass",
                "(Ljava/lang/String;Ljava/lang/ClassLoader;Ljava/lang/Object;Ljava/util/List;)Ljava/lang/Class;",
                JD_GRAPH_NODE_LOAD_DEX 
        },
        {
                "Ljava/lang/invoke/MethodHandles$Lookup;",
                "defineClass",
                "([B)Ljava/lang/Class;",
                JD_GRAPH_NODE_LOAD_DEX 
        },
        {
                "Ljava/security/cert/X509Certificate;",
                "getExtensionValue",
                "(Ljava/lang/String;)[B",
                JD_GRAPH_NODE_LOAD_DEX 
        },
        {
                "Ljava/lang/System;",
                "load",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_LOAD_SO
        },
        {
                "Ljava/lang/System;",
                "loadLibrary",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_LOAD_SO
        },
        {
                "Ljava/lang/Runtime;",
                "loadLibrary",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_LOAD_SO
        },
        {
                "Ljava/lang/System;",
                "mapLibraryName",
                "(Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_LOAD_SO
        },
        {
                "Ljava/lang/Class;",
                "forName",
                "(Ljava/lang/String;)Ljava/lang/Class;",
                JD_GRAPH_NODE_REFLECTION
        },
        {
                "Ljava/lang/Class;",
                "getMethod",
                "(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;",
                JD_GRAPH_NODE_REFLECTION
        },
        {
                "Ljava/lang/Class;",
                "getDeclaredMethod",
                "(Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method;",
                JD_GRAPH_NODE_REFLECTION
        },
        {
                "Ljava/lang/reflect/Method;",
                "invoke",
                "(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;",
                JD_GRAPH_NODE_REFLECTION
        },
        { "Landroid/os/ServiceManager;", "getService", "(Ljava/lang/String;)Landroid/os/IBinder;", JD_GRAPH_NODE_REFLECTION },
        {
                "Ljava/lang/Class;",
                "getDeclaredField",
                "(Ljava/lang/String;)Ljava/lang/reflect/Field;",
                JD_GRAPH_NODE_REFLECTION
        },
        {
                "Ljava/lang/Class;",
                "getField",
                "(Ljava/lang/String;)Ljava/lang/reflect/Field;",
                JD_GRAPH_NODE_REFLECTION
        },
        {
                "Ljava/lang/reflect/Field;",
                "get",
                "(Ljava/lang/Object;)Ljava/lang/Object;",
                JD_GRAPH_NODE_REFLECTION
        },
        {
                "Ljava/lang/reflect/Field;",
                "set",
                "(Ljava/lang/Object;Ljava/lang/Object;)V",
                JD_GRAPH_NODE_REFLECTION
        },
        {
                "Ljava/lang/reflect/Constructor;",
                "newInstance",
                "([Ljava/lang/Object;)Ljava/lang/Object;",
                JD_GRAPH_NODE_REFLECTION
        },
        {
                "Ljava/lang/Class;",
                "getSlot",
                "()I",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/reflect/AccessibleObject;",
                "setAccessible",
                "([Ljava/lang/reflect/AccessibleObject;Z)V",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Landroid/os/ServiceManager;",
                "checkService",
                "(Ljava/lang/String;)Landroid/os/IBinder;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Landroid/app/ActivityThread;",
                "getPackageManager",
                "()Landroid/content/pm/IPackageManager;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/invoke/MethodHandles$Lookup;",
                "findVirtual",
                "(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/MethodHandle;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/invoke/MethodHandle;",
                "invokeExact",
                "([Ljava/lang/Object;)Ljava/lang/Object;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/reflect/Proxy;",
                "newProxyInstance",
                "(Ljava/lang/ClassLoader;[Ljava/lang/Class;Ljava/lang/reflect/InvocationHandler;)Ljava/lang/Object;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/reflect/Proxy;",
                "getInvocationHandler",
                "(Ljava/lang/Object;)Ljava/lang/reflect/InvocationHandler;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ldalvik/system/VMRuntime;",
                "setHiddenApiExemptions",
                "([Ljava/lang/String;)V",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/invoke/MethodHandles;",
                "privateLookupIn",
                "(Ljava/lang/Class;Ljava/lang/invoke/MethodHandles$Lookup;)Ljava/lang/invoke/MethodHandles$Lookup;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/Class;",
                "getDeclaredFields",
                "()[Ljava/lang/reflect/Field;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/reflect/Constructor;",
                "newInstance",
                "([Ljava/lang/Object;)Ljava/lang/Object;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/invoke/MethodHandles$Lookup;",
                "findVirtual",
                "(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/MethodHandle;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/invoke/MethodHandles$Lookup;",
                "findStaticSetter",
                "(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/invoke/MethodHandle;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/invoke/MethodHandle;",
                "invokeExact",
                "([Ljava/lang/Object;)Ljava/lang/Object;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/invoke/MethodHandles;",
                "privateLookupIn",
                "(Ljava/lang/Class;Ljava/lang/invoke/MethodHandles$Lookup;)Ljava/lang/invoke/MethodHandles$Lookup;",
                JD_GRAPH_NODE_REFLECTION 
        },
        {
                "Ljava/lang/reflect/Proxy;",
                "newProxyInstance",
                "(Ljava/lang/ClassLoader;[Ljava/lang/Class;Ljava/lang/reflect/InvocationHandler;)Ljava/lang/Object;",
                JD_GRAPH_NODE_REFLECTION 
        },
        
        {
                "Ljava/lang/Runtime;",
                "exec",
                "(Ljava/lang/String;)Ljava/lang/Process;",
                JD_GRAPH_NODE_EXEC_CMD
        },
        {
                "Ljava/lang/Runtime;",
                "exec",
                "([Ljava/lang/String;)Ljava/lang/Process;",
                JD_GRAPH_NODE_EXEC_CMD
        },
        {
                "Ljava/lang/ProcessBuilder;",
                "start",
                "()Ljava/lang/Process;",
                JD_GRAPH_NODE_EXEC_CMD
        },
        { "Ljava/lang/Runtime;", "exec", "(Ljava/lang/String;)Ljava/lang/Process;", JD_GRAPH_NODE_EXEC_CMD },
        {
                "Landroid/app/ActivityManager;",
                "killBackgroundProcesses",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_EXEC_CMD 
        },
        {
                "Landroid/os/Process;",
                "sendSignal",
                "(II)V",
                JD_GRAPH_NODE_EXEC_CMD 
        },
        {
                "Landroid/os/Process;",
                "killProcess",
                "(I)V",
                JD_GRAPH_NODE_EXEC_CMD 
        },
        {
                "Landroid/view/accessibility/AccessibilityNodeInfo;",
                "performAction",
                "(I)Z", 
                JD_GRAPH_NODE_EXEC_CMD 
        },
        {
                "Landroid/view/accessibility/AccessibilityNodeInfo;",
                "performAction",
                "(I)Z",
                JD_GRAPH_NODE_EXEC_CMD 
        },
        {
                "Landroid/content/RestrictionsManager;",
                "notifyPermissionResponse",
                "(Ljava/lang/String;Landroid/os/PersistableBundle;)V",
                JD_GRAPH_NODE_EXEC_CMD 
        },
        {
                "Landroid/content/RestrictionsManager;",
                "createLocalApprovalIntent",
                "(Ljava/lang/String;Landroid/os/PersistableBundle;)Landroid/content/Intent;",
                JD_GRAPH_NODE_EXEC_CMD 
        },
        {
                "Landroid/appwidget/AppWidgetManager;",
                "bindAppWidgetIdIfAllowed",
                "(ILandroid/content/ComponentName;)Z",
                JD_GRAPH_NODE_EXEC_CMD 
        },
        {
                "Landroid/companion/CompanionDeviceManager;",
                "disassociate",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_EXEC_CMD 
        },
        
        {
                "Landroid/webkit/WebView;",
                "loadUrl",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_WEBVIEW_LOAD_URL
        },
        {
                "Landroid/webkit/WebView;",
                "postUrl",
                "(Ljava/lang/String;[B)V",
                JD_GRAPH_NODE_WEBVIEW_LOAD_URL
        },
        {
                "Landroid/webkit/WebView;",
                "evaluateJavascript",
                "(Ljava/lang/String;Landroid/webkit/ValueCallback;)V",
                JD_GRAPH_NODE_WEBVIEW_EVAL_JS
        },
        {
                "Landroid/webkit/WebView;",
                "addJavascriptInterface",
                "(Ljava/lang/Object;Ljava/lang/String;)V",
                JD_GRAPH_NODE_WEBVIEW_EVAL_JS 
        },
        {
                "Landroid/webkit/WebSettings;",
                "setJavaScriptEnabled",
                "(Z)V",
                JD_GRAPH_NODE_WEBVIEW_EVAL_JS
        },
        
        {
                "Landroid/os/SystemProperties;",
                "get",
                "(Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_GET_SYSTEM_PROPERTY
        },
        {
                "Landroid/os/SystemProperties;",
                "get",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_GET_SYSTEM_PROPERTY
        },
        { "Ljava/lang/System;", "getProperty", "(Ljava/lang/String;)Ljava/lang/String;", JD_GRAPH_NODE_GET_SYSTEM_PROPERTY },
        {
                "Ljava/lang/System;",
                "getenv",
                "(Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_GET_SYSTEM_PROPERTY
        },
        {
                "Landroid/content/res/Configuration;",
                "setToDefaults",
                "()V",
                JD_GRAPH_NODE_GET_SYSTEM_PROPERTY 
        },
        {
                "Landroid/provider/Settings$System;",
                "getString",
                "(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_GET_SYSTEM_PROPERTY 
        },
        {
                "Landroid/provider/Settings$System;",
                "getString",
                "(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_GET_SYSTEM_PROPERTY 
        },
        
        {
                "Ljava/io/File;",
                "canExecute",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/Process;",
                "is64Bit",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/net/NetworkInterface;",
                "getNetworkInterfaces",
                "()Ljava/util/Enumeration;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/System;",
                "runFinalization",
                "()V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ldalvik/system/VMRuntime;",
                "getRuntime",
                "()Ldalvik/system/VMRuntime;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/Runtime;",
                "halt",
                "(I)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/PowerManager;",
                "isInteractive",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/net/NetworkInterface;",
                "getInetAddresses",
                "()Ljava/util/Enumeration;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/Runtime;",
                "totalMemory",
                "()J",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/Runtime;",
                "availableProcessors",
                "()I",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/content/pm/Signature;",
                "toByteArray",
                "()[B",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/SystemClock;",
                "sleep",
                "(J)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/Process;",
                "setThreadPriority",
                "(II)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/StrictMode;",
                "setThreadPolicy",
                "(Landroid/os/StrictMode$ThreadPolicy;)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/util/Locale;",
                "getDefault",
                "()Ljava/util/Locale;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "getNetworkCountryIso",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/ThreadGroup;",
                "destroy",
                "()V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/view/Display;",
                "getRefreshRate",
                "()F",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/view/Display;",
                "getHdrCapabilities",
                "()Landroid/view/Display$HdrCapabilities;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/Process;",
                "setProcessGroup",
                "(II)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/content/pm/PackageManager;",
                "getComponentEnabledSetting",
                "(Landroid/content/ComponentName;)I",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/Runtime;",
                "gc",
                "()V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/net/NetworkInterface;",
                "getMTU",
                "()I",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/UserManager;",
                "getUserProfiles",
                "()Ljava/util/List;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/UserManager;",
                "isUserAMonkey",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/app/NotificationManager;",
                "areNotificationsEnabled",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/net/NetworkInterface;",
                "isLoopback",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/storage/StorageManager;",
                "getStorageVolumes",
                "()Ljava/util/List;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/StatFs;",
                "restat",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/BatteryManager;",
                "getIntProperty",
                "(I)I",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/Class;",
                "getEnclosingMethod",
                "()Ljava/lang/reflect/Method;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/ClassLoader;",
                "findLibrary",
                "(Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/net/Socket;",
                "getTrafficClass",
                "()I",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/bluetooth/BluetoothAdapter;",
                "getAddress",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/bluetooth/BluetoothAdapter;",
                "getName",
                "()Ljava/lang/String;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/bluetooth/BluetoothAdapter;",
                "getState",
                "()I",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/bluetooth/BluetoothAdapter;",
                "disable",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/provider/Settings$Secure;",
                "getString",
                "(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/provider/Settings$Global;",
                "getString",
                "(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/provider/Settings;",
                "canDrawOverlays",
                "(Landroid/content/Context;)Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/location/LocationManager;",
                "removeUpdates",
                "(Landroid/location/LocationListener;)V", 
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/location/LocationManager;",
                "getProviders",
                "(Z)Ljava/util/List;", 
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/location/LocationManager;",
                "isProviderEnabled",
                "(Ljava/lang/String;)Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/nfc/NfcAdapter;",
                "isEnabled",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/nfc/cardemulation/CardEmulation;",
                "isDefaultServiceForCategory",
                "(Landroid/content/ComponentName;Ljava/lang/String;)Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/hardware/SensorManager;",
                "getDefaultSensor",
                "(I)Landroid/hardware/Sensor;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/hardware/fingerprint/FingerprintManager;", 
                "isHardwareDetected",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/hardware/fingerprint/FingerprintManager;",
                "hasEnrolledFingerprints",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/hardware/biometrics/BiometricManager;",
                "canAuthenticate",
                "(I)I", 
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/Debug;",
                "isDebuggerConnected",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/provider/Settings$Secure;",
                "getString",
                "(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/provider/Settings$Global;",
                "getString",
                "(Landroid/content/ContentResolver;Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/provider/Settings;",
                "canDrawOverlays",
                "(Landroid/content/Context;)Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/location/LocationManager;",
                "removeUpdates",
                "(Landroid/location/LocationListener;)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/location/LocationManager;",
                "isProviderEnabled",
                "(Ljava/lang/String;)Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/nfc/NfcAdapter;",
                "isEnabled",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/hardware/fingerprint/FingerprintManager;", 
                "isHardwareDetected",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/System;",
                "runFinalization",
                "()V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/Runtime;",
                "availableProcessors",
                "()I",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/SharedMemory;",
                "unmap",
                "(Ljava/nio/ByteBuffer;)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/security/keystore/KeyInfo;",
                "isInsideSecureHardware",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/lang/Thread;",
                "setDefaultUncaughtExceptionHandler",
                "(Ljava/lang/Thread$UncaughtExceptionHandler;)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Ljava/security/KeyStore;",
                "aliases",
                "()Ljava/util/Enumeration;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/security/keystore/KeyInfo;",
                "isInsideSecureHardware",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/net/ConnectivityManager;",
                "getNetworkCapabilities",
                "(Landroid/net/Network;)Landroid/net/NetworkCapabilities;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/net/NetworkCapabilities;",
                "hasTransport",
                "(I)Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/BatteryManager;",
                "isCharging",
                "()Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/PowerManager;",
                "isIgnoringBatteryOptimizations",
                "(Ljava/lang/String;)Z",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/media/projection/MediaProjection;",
                "registerCallback",
                "(Landroid/media/projection/MediaProjection$Callback;Landroid/os/Handler;)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/view/ViewTreeObserver;",
                "addOnGlobalFocusChangeListener",
                "(Landroid/view/ViewTreeObserver$OnGlobalFocusChangeListener;)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/hardware/usb/UsbManager;",
                "getDeviceList",
                "()Ljava/util/HashMap;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/os/health/SystemHealthManager;",
                "takeMyUidSnapshot",
                "()Landroid/os/health/HealthStats;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/content/RestrictionsManager;",
                "getApplicationRestrictions",
                "(Ljava/lang/String;)Landroid/os/Bundle;",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        {
                "Landroid/net/wifi/rtt/RttManager;",
                "startRanging",
                "(Landroid/net/wifi/rtt/RangingRequest;Landroid/net/wifi/rtt/RangingResultCallback;)V",
                JD_GRAPH_NODE_ANTI_DEBUG 
        },
        
        { "Landroid/content/Context;", "registerReceiver", "(Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;)Landroid/content/Intent;", JD_GRAPH_NODE_DYNAMIC_RECEIVER },
        {
                "Landroid/content/IntentFilter;",
                "addAction",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_DYNAMIC_RECEIVER 
        },
        { "Landroid/content/Context;", "startActivity", "(Landroid/content/Intent;)V", JD_GRAPH_NODE_START_ACTIVITY },
        {
                "Landroid/app/IActivityManager;",
                "startActivity",
                "(Landroid/app/IApplicationThread;Ljava/lang/String;Landroid/content/Intent;Ljava/lang/String;Landroid/os/IBinder;Ljava/lang/String;IILandroid/app/ProfilerInfo;Landroid/os/Bundle;)I",
                JD_GRAPH_NODE_START_ACTIVITY 
        },
        {
                "Landroid/app/Activity;",
                "startActivityAsUser",
                "(Landroid/content/Intent;Landroid/os/UserHandle;)V",
                JD_GRAPH_NODE_START_ACTIVITY 
        },
        { "Landroid/content/Context;", "sendBroadcast", "(Landroid/content/Intent;)V", JD_GRAPH_NODE_SEND_BROADCAST },
        {
                "Landroid/content/Intent;",
                "setPackage",
                "(Ljava/lang/String;)Ljava/lang/String;",
                JD_GRAPH_NODE_SEND_BROADCAST 
        },
        { "Landroid/app/Service;", "startForeground", "(ILandroid/app/Notification;)V", JD_GRAPH_NODE_START_SERVICE },
        
        { "Landroid/content/ContentResolver;", "setIsSyncable", "(Landroid/accounts/Account;Ljava/lang/String;I)V", JD_GRAPH_NODE_PERSISTENCE },
        { "Landroid/app/job/JobScheduler;", "schedule", "(Landroid/app/job/JobInfo;)I", JD_GRAPH_NODE_PERSISTENCE },
        {
                "Landroid/os/WorkManager;",
                "enqueue",
                "(Landroidx/work/WorkRequest;)Landroid/os/Operation;",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/accounts/AccountManager;",
                "addAccountExplicitly",
                "(Landroid/accounts/Account;Ljava/lang/String;Landroid/os/Bundle;)Z",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/os/PowerManager;",
                "newWakeLock",
                "(ILjava/lang/String;)Landroid/os/PowerManager$WakeLock;",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/os/PowerManager$WakeLock;",
                "acquire",
                "()V",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/os/HandlerThread;",
                "getLooper",
                "()Landroid/os/Looper;",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/media/session/MediaSession;",
                "setActive",
                "(Z)V",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/bluetooth/BluetoothAdapter;",
                "enable",
                "()Z",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/provider/Settings$Secure;",
                "putInternal", 
                "(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;)Z",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/provider/Settings$Global;",
                "putInt",
                "(Landroid/content/ContentResolver;Ljava/lang/String;I)Z",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/provider/Settings$Secure;",
                "putString",
                "(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;)Z",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/provider/Settings$Global;",
                "putInt",
                "(Landroid/content/ContentResolver;Ljava/lang/String;I)Z",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/media/session/MediaSession;",
                "setActive",
                "(Z)V",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/os/FileObserver;",
                "startWatching",
                "()V",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/os/health/SystemHealthManager;",
                "takeUidSnapshot",
                "(I)Landroid/os/health/HealthStats;",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/os/health/HealthStats;",
                "getMeasurement",
                "(I)J", 
                JD_GRAPH_NODE_PERSISTENCE 
        },
        {
                "Landroid/companion/CompanionDeviceManager;",
                "hasAssociation",
                "()Z",
                JD_GRAPH_NODE_PERSISTENCE 
        },
        
        {
                "Landroid/app/Notification$Builder;",
                "setFullScreenIntent",
                "(Landroid/app/PendingIntent;Z)Landroid/app/Notification$Builder;",
                JD_GRAPH_NODE_OVERLAY_ATTACK 
        },
        
        { "Landroid/os/IBinder;", "transact", "(ILandroid/os/Parcel;Landroid/os/Parcel;I)Z", JD_GRAPH_NODE_BINDER_TRANSACT },
        {
                "Landroid/os/Parcel;",
                "obtain",
                "()Landroid/os/Parcel;",
                JD_GRAPH_NODE_BINDER_TRANSACT
        },
        {
                "Landroid/os/Parcel;",
                "writeInterfaceToken",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_BINDER_TRANSACT
        },
        {
                "Landroid/os/Binder;",
                "clearCallingIdentity",
                "()J",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Landroid/os/IBinder;",
                "linkToDeath",
                "(Landroid/os/IBinder$DeathRecipient;I)V",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Landroid/os/Parcel;",
                "marshall",
                "()[B",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Landroid/os/Parcel;",
                "unmarshall",
                "([BII)V",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Landroid/nfc/cardemulation/HostApduService;",
                "processCommandApdu",
                "([BLandroid/os/Bundle;)[B",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Landroid/nfc/cardemulation/HostApduService;",
                "processCommandApdu",
                "([BLandroid/os/Bundle;)[B",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Landroid/hardware/usb/UsbDeviceConnection;",
                "claimInterface",
                "(Landroid/hardware/usb/UsbInterface;Z)Z",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Landroid/hardware/usb/UsbDeviceConnection;",
                "controlTransfer",
                "(IIII[BII)I",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Landroid/webkit/CookieManager;",
                "getInstance",
                "()Landroid/webkit/CookieManager;",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Landroid/companion/CompanionDeviceManager;",
                "associate",
                "(Landroid/companion/AssociationRequest;Landroid/companion/CompanionDeviceManager$Callback;Landroid/os/Handler;)V",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        {
                "Ljavax/net/ssl/KeyManagerFactory;",
                "getInstance",
                "(Ljava/lang/String;)Ljavax/net/ssl/KeyManagerFactory;",
                JD_GRAPH_NODE_BINDER_TRANSACT 
        },
        
        { "Landroid/accessibilityservice/AccessibilityService;", "dispatchGesture", "(Landroid/accessibilityservice/GestureDescription;Landroid/accessibilityservice/AccessibilityService$GestureResultCallback;Landroid/os/Handler;)Z", JD_GRAPH_NODE_ACCESSIBILITY_EXPL },
        
        { "Landroid/view/accessibility/AccessibilityEvent;", "getText", "()Ljava/util/List;", JD_GRAPH_NODE_KEYLOGGING },
        {
                "Landroid/view/accessibility/AccessibilityEvent;",
                "getPackageName",
                "()Ljava/lang/CharSequence;",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "getCallState",
                "()I",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/telephony/TelephonyManager;",
                "listen",
                "(Landroid/telephony/PhoneStateListener;I)V",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/app/Application;",
                "registerActivityLifecycleCallbacks",
                "(Landroid/app/Application$ActivityLifecycleCallbacks;)V",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/view/InputEvent;",
                "getDevice",
                "()Landroid/view/InputDevice;",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/hardware/SensorManager;",
                "registerListener",
                "(Landroid/hardware/SensorEventListener;Landroid/hardware/Sensor;I)Z",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/view/accessibility/AccessibilityNodeInfo;",
                "getChild",
                "(I)Landroid/view/accessibility/AccessibilityNodeInfo;",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/view/accessibility/AccessibilityNodeInfo;",
                "getChild",
                "(I)Landroid/view/accessibility/AccessibilityNodeInfo;",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/inputmethodservice/InputMethodService;",
                "onStartInput",
                "(Landroid/view/inputmethod/EditorInfo;Z)V",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/view/inputmethod/InputConnection;",
                "commitText",
                "(Ljava/lang/CharSequence;I)Z",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/view/inputmethod/InputConnection;",
                "getTextBeforeCursor",
                "(II)Ljava/lang/CharSequence;", 
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/view/View;",
                "onKeyDown",
                "(ILandroid/view/KeyEvent;)Z", 
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/telephony/SmsManager;",
                "sendTextMessage",
                "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid/app/PendingIntent;Landroid/app/PendingIntent;)V",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/telephony/SmsManager;",
                "divideMessage",
                "(Ljava/lang/String;)Ljava/util/ArrayList;",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        {
                "Landroid/view/autofill/AutofillManager;",
                "requestAutofill",
                "(Landroid/view/View;)V",
                JD_GRAPH_NODE_KEYLOGGING 
        },
        
        {
          "Landroid/content/pm/PackageManager;",
          "setComponentEnabledSetting",
          "(Landroid/content/ComponentName;II)V",
          JD_GRAPH_NODE_HIDE_ICON
        },
        
        { 
          "Landroid/app/admin/DevicePolicyManager;", "isAdminActive", "(Landroid/content/ComponentName;)Z", JD_GRAPH_NODE_DEVICE_ADMIN 
        },
        
        { "Landroid/content/ContentProvider;", "openFile", "(Landroid/net/Uri;Ljava/lang/String;)Landroid/os/ParcelFileDescriptor;", JD_GRAPH_NODE_PROVIDER_EXPOSE },
        
        {
                "Landroid/app/Activity;",
                "setFinishOnTouchOutside",
                "(Z)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/app/NotificationManager;",
                "setInterruptionFilter",
                "(I)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/app/ActivityManager;",
                "moveTaskToBack",
                "(ZI)Z",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/app/KeyguardManager;",
                "newKeyguardLock",
                "(Ljava/lang/String;)Landroid/app/KeyguardManager$KeyguardLock;",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/media/AudioManager;",
                "setStreamVolume",
                "(III)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/media/AudioManager;",
                "setRingerMode",
                "(I)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/os/Vibrator;",
                "vibrate",
                "(J)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/app/WallpaperManager;",
                "setBitmap",
                "(Landroid/graphics/Bitmap;Landroid/graphics/Rect;Z)I",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/app/NotificationManager;",
                "deleteNotificationChannel",
                "(Ljava/lang/String;)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/provider/Settings$System;",
                "putStream", 
                "(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;)Z",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/hardware/fingerprint/FingerprintManager;",
                "authenticate",
                "(Landroid/hardware/fingerprint/FingerprintManager$CryptoObject;Landroid/os/CancellationSignal;ILandroid/hardware/fingerprint/FingerprintManager$AuthenticationCallback;Landroid/os/Handler;)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/hardware/biometrics/BiometricPrompt;",
                "authenticate",
                "(Landroid/hardware/biometrics/BiometricPrompt$CryptoObject;Landroid/os/CancellationSignal;Ljava/util/concurrent/Executor;Landroid/hardware/biometrics/BiometricPrompt$AuthenticationCallback;)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/provider/Settings$System;",
                "putString",
                "(Landroid/content/ContentResolver;Ljava/lang/String;Ljava/lang/String;)Z",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/hardware/biometrics/BiometricPrompt;",
                "authenticate",
                "(Landroid/hardware/biometrics/BiometricPrompt$CryptoObject;Landroid/os/CancellationSignal;Ljava/util/concurrent/Executor;Landroid/hardware/biometrics/BiometricPrompt$AuthenticationCallback;)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/appwidget/AppWidgetManager;",
                "updateAppWidget",
                "(Landroid/content/ComponentName;Landroid/widget/RemoteViews;)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/appwidget/AppWidgetProvider;",
                "onUpdate",
                "(Landroid/content/Context;Landroid/appwidget/AppWidgetManager;[I)V",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        {
                "Landroid/content/pm/ShortcutManager;",
                "addDynamicShortcuts",
                "(Ljava/util/List;)Z",
                JD_GRAPH_NODE_SCREEN_LOCK 
        },
        
        {
                "Landroid/content/Intent;",
                "getParcelableExtra",
                "(Ljava/lang/String;)Landroid/os/Parcelable;",
                JD_GRAPH_NODE_INTENT_REDIRECT 
        },
        {
                "Landroid/content/Intent;",
                "fillIn",
                "(Landroid/content/Intent;I)I",
                JD_GRAPH_NODE_INTENT_REDIRECT 
        },
        {
                "Landroid/app/PendingIntent;",
                "getIntentSender",
                "()Landroid/content/IntentSender;",
                JD_GRAPH_NODE_INTENT_REDIRECT 
        },
        {
                "Landroid/content/Intent;",
                "getIntent",
                "(Ljava/lang/String;)Landroid/content/Intent;",
                JD_GRAPH_NODE_INTENT_REDIRECT 
        },
        {
                "Landroid/os/Bundle;",
                "getSerializable",
                "(Ljava/lang/String;)Ljava/io/Serializable;",
                JD_GRAPH_NODE_INTENT_REDIRECT 
        },
        {
                "Landroid/app/PendingIntent;",
                "send",
                "(Landroid/content/Context;ILandroid/content/Intent;Landroid/app/PendingIntent$OnFinished;Landroid/os/Handler;Ljava/lang/String;Landroid/os/Bundle;)V",
                JD_GRAPH_NODE_INTENT_REDIRECT 
        },
        {
                "Landroid/nfc/NfcAdapter;",
                "enableForegroundDispatch",
                "(Landroid/app/Activity;Landroid/app/PendingIntent;[Landroid/content/IntentFilter;[[Ljava/lang/String;)V",
                JD_GRAPH_NODE_INTENT_REDIRECT 
        },
        {
                "Landroid/nfc/NfcAdapter;",
                "enableForegroundDispatch",
                "(Landroid/app/Activity;Landroid/app/PendingIntent;[Landroid/content/IntentFilter;[[Ljava/lang/String;)V",
                JD_GRAPH_NODE_INTENT_REDIRECT 
        },
};

const char* jd_api_type_to_string(jd_graph_api_type type);

#endif 
