#include "hashmap_tools.h"
#include "metadata.h"

string jvm_opcode_name(u1 code)
{
    switch(code) {
        case  0x00:
            return  "nop";
        case  0x01:
            return  "aconst_null";
        case  0x02:
            return  "iconst_m1";
        case  0x03:
            return  "iconst_0";
        case  0x04:
            return  "iconst_1";
        case  0x05:
            return  "iconst_2";
        case  0x06:
            return  "iconst_3";
        case  0x07:
            return  "iconst_4";
        case  0x08:
            return  "iconst_5";
        case  0x09:
            return  "lconst_0";
        case  0x0a:
            return  "lconst_1";
        case  0x0b:
            return  "fconst_0";
        case  0x0c:
            return  "fconst_1";
        case  0x0d:
            return  "fconst_2";
        case  0x0e:
            return  "dconst_0";
        case  0x0f:
            return  "dconst_1";
        case  0x10:
            return  "bipush";
        case  0x11:
            return  "sipush";
        case  0x12:
            return  "ldc";
        case  0x13:
            return  "ldc_w";
        case  0x14:
            return  "ldc2_w";
        case  0x15:
            return  "iload";
        case  0x16:
            return  "lload";
        case  0x17:
            return  "fload";
        case  0x18:
            return  "dload";
        case  0x19:
            return  "aload";
        case  0x1a:
            return  "iload_0";
        case  0x1b:
            return  "iload_1";
        case  0x1c:
            return  "iload_2";
        case  0x1d:
            return  "iload_3";
        case  0x1e:
            return  "lload_0";
        case  0x1f:
            return  "lload_1";
        case  0x20:
            return  "lload_2";
        case  0x21:
            return  "lload_3";
        case  0x22:
            return  "fload_0";
        case  0x23:
            return  "fload_1";
        case  0x24:
            return  "fload_2";
        case  0x25:
            return  "fload_3";
        case  0x26:
            return  "dload_0";
        case  0x27:
            return  "dload_1";
        case  0x28:
            return  "dload_2";
        case  0x29:
            return  "dload_3";
        case  0x2a:
            return  "aload_0";
        case  0x2b:
            return  "aload_1";
        case  0x2c:
            return  "aload_2";
        case  0x2d:
            return  "aload_3";
        case  0x2e:
            return  "iaload";
        case  0x2f:
            return  "laload";
        case  0x30:
            return  "faload";
        case  0x31:
            return  "daload";
        case  0x32:
            return  "aaload";
        case  0x33:
            return  "baload";
        case  0x34:
            return  "caload";
        case  0x35:
            return  "saload";
        case  0x36:
            return  "istore";
        case  0x37:
            return  "lstore";
        case  0x38:
            return  "fstore";
        case  0x39:
            return  "dstore";
        case  0x3a:
            return  "astore";
        case  0x3b:
            return  "istore_0";
        case  0x3c:
            return  "istore_1";
        case  0x3d:
            return  "istore_2";
        case  0x3e:
            return  "istore_3";
        case  0x3f:
            return  "lstore_0";
        case  0x40:
            return  "lstore_1";
        case  0x41:
            return  "lstore_2";
        case  0x42:
            return  "lstore_3";
        case  0x43:
            return  "fstore_0";
        case  0x44:
            return  "fstore_1";
        case  0x45:
            return  "fstore_2";
        case  0x46:
            return  "fstore_3";
        case  0x47:
            return  "dstore_0";
        case  0x48:
            return  "dstore_1";
        case  0x49:
            return  "dstore_2";
        case  0x4a:
            return  "dstore_3";
        case  0x4b:
            return  "astore_0";
        case  0x4c:
            return  "astore_1";
        case  0x4d:
            return  "astore_2";
        case  0x4e:
            return  "astore_3";
        case  0x4f:
            return  "iastore";
        case  0x50:
            return  "lastore";
        case  0x51:
            return  "fastore";
        case  0x52:
            return  "dastore";
        case  0x53:
            return  "aastore";
        case  0x54:
            return  "bastore";
        case  0x55:
            return  "castore";
        case  0x56:
            return  "sastore";
        case  0x57:
            return  "pop";
        case  0x58:
            return  "pop2";
        case  0x59:
            return  "dup";
        case  0x5a:
            return  "dup_x1";
        case  0x5b:
            return  "dup_x2";
        case  0x5c:
            return  "dup2";
        case  0x5d:
            return  "dup2_x1";
        case  0x5e:
            return  "dup2_x2";
        case  0x5f:
            return  "swap";
        case  0x60:
            return  "iadd";
        case  0x61:
            return  "ladd";
        case  0x62:
            return  "fadd";
        case  0x63:
            return  "dadd";
        case  0x64:
            return  "isub";
        case  0x65:
            return  "lsub";
        case  0x66:
            return  "fsub";
        case  0x67:
            return  "dsub";
        case  0x68:
            return  "imul";
        case  0x69:
            return  "lmul";
        case  0x6a:
            return  "fmul";
        case  0x6b:
            return  "dmul";
        case  0x6c:
            return  "idiv";
        case  0x6d:
            return  "ldiv";
        case  0x6e:
            return  "fdiv";
        case  0x6f:
            return  "ddiv";
        case  0x70:
            return  "irem";
        case  0x71:
            return  "lrem";
        case  0x72:
            return  "frem";
        case  0x73:
            return  "drem";
        case  0x74:
            return  "ine";
        case  0x75:
            return  "lne";
        case  0x76:
            return  "fne";
        case  0x77:
            return  "dne";
        case  0x78:
            return  "ishl";
        case  0x79:
            return  "lshl";
        case  0x7a:
            return  "ishr";
        case  0x7b:
            return  "lshr";
        case  0x7c:
            return  "iushr";
        case  0x7d:
            return  "lushr";
        case  0x7e:
            return  "iand";
        case  0x7f:
            return  "land";
        case  0x80:
            return  "ior";
        case  0x81:
            return  "lor";
        case  0x82:
            return  "ixor";
        case  0x83:
            return  "lxor";
        case  0x84:
            return  "iinc";
        case  0x85:
            return  "i2l";
        case  0x86:
            return  "i2f";
        case  0x87:
            return  "i2d";
        case  0x88:
            return  "l2i";
        case  0x89:
            return  "l2f";
        case  0x8a:
            return  "l2d";
        case  0x8b:
            return  "f2i";
        case  0x8c:
            return  "f2l";
        case  0x8d:
            return  "f2d";
        case  0x8e:
            return  "d2i";
        case  0x8f:
            return  "d2l";
        case  0x90:
            return  "d2f";
        case  0x91:
            return  "i2b";
        case  0x92:
            return  "i2c";
        case  0x93:
            return  "i2s";
        case  0x94:
            return  "lcmp";
        case  0x95:
            return  "fcmpl";
        case  0x96:
            return  "fcmp";
        case  0x97:
            return  "dcmpl";
        case  0x98:
            return  "dcmp";
        case  0x99:
            return  "ifeq";
        case  0x9a:
            return  "ifne";
        case  0x9b:
            return  "iflt";
        case  0x9c:
            return  "ifge";
        case  0x9d:
            return  "ifgt";
        case  0x9e:
            return  "ifle";
        case  0x9f:
            return  "if_icmpeq";
        case  0xa0:
            return  "if_icmpne";
        case  0xa1:
            return  "if_icmplt";
        case  0xa2:
            return  "if_icmpge";
        case  0xa3:
            return  "if_icmpgt";
        case  0xa4:
            return  "if_icmple";
        case  0xa5:
            return  "if_acmpeq";
        case  0xa6:
            return  "if_acmpne";
        case  0xa7:
            return  "goto";
        case  0xa8:
            return  "jsr";
        case  0xa9:
            return  "ret";
        case  0xaa:
            return  "tableswitch";
        case  0xab:
            return  "lookupswitch";
        case  0xac:
            return  "ireturn";
        case  0xad:
            return  "lreturn";
        case  0xae:
            return  "freturn";
        case  0xaf:
            return  "dreturn";
        case  0xb0:
            return  "areturn";
        case  0xb1:
            return  "return";
        case  0xb2:
            return  "getstatic";
        case  0xb3:
            return  "putstatic";
        case  0xb4:
            return  "getfield";
        case  0xb5:
            return  "putfield";
        case  0xb6:
            return  "invokevirtual";
        case  0xb7:
            return  "invokespecial";
        case  0xb8:
            return  "invokestatic";
        case  0xb9:
            return  "invokeinterface";
        case  0xba:
            return  "invokedynamic";
        case  0xbb:
            return  "new";
        case  0xbc:
            return  "newarray";
        case  0xbd:
            return  "anewarray";
        case  0xbe:
            return  "arraylength";
        case  0xbf:
            return  "athrow";
        case  0xc0:
            return  "checkcast";
        case  0xc1:
            return  "instanceof";
        case  0xc2:
            return  "monitorenter";
        case  0xc3:
            return  "monitorexit";
        case  0xc4:
            return  "wide";
        case  0xc5:
            return  "multianewarray";
        case  0xc6:
            return  "ifnull";
        case  0xc7:
            return  "ifnonnull";
        case  0xc8:
            return  "goto_w";
        case  0xc9:
            return  "jsr_w";
        case  0xca:
            return  "breakpoint";
        case  0xfe:
            return  "impdep1";
        case  0xff:
            return  "leavefinally";
        default:
            return "unknown";
    }
}

int jvm_opcode_popped(u1 code)
{
    switch(code) {
        case  0x00:
            return  0;
        case  0x01:
            return  0;
        case  0x02:
            return  0;
        case  0x03:
            return  0;
        case  0x04:
            return  0;
        case  0x05:
            return  0;
        case  0x06:
            return  0;
        case  0x07:
            return  0;
        case  0x08:
            return  0;
        case  0x09:
            return  0;
        case  0x0a:
            return  0;
        case  0x0b:
            return  0;
        case  0x0c:
            return  0;
        case  0x0d:
            return  0;
        case  0x0e:
            return  0;
        case  0x0f:
            return  0;
        case  0x10:
            return  0;
        case  0x11:
            return  0;
        case  0x12:
            return  0;
        case  0x13:
            return  0;
        case  0x14:
            return  0;
        case  0x15:
            return  0;
        case  0x16:
            return  0;
        case  0x17:
            return  0;
        case  0x18:
            return  0;
        case  0x19:
            return  0;
        case  0x1a:
            return  0;
        case  0x1b:
            return  0;
        case  0x1c:
            return  0;
        case  0x1d:
            return  0;
        case  0x1e:
            return  0;
        case  0x1f:
            return  0;
        case  0x20:
            return  0;
        case  0x21:
            return  0;
        case  0x22:
            return  0;
        case  0x23:
            return  0;
        case  0x24:
            return  0;
        case  0x25:
            return  0;
        case  0x26:
            return  0;
        case  0x27:
            return  0;
        case  0x28:
            return  0;
        case  0x29:
            return  0;
        case  0x2a:
            return  0;
        case  0x2b:
            return  0;
        case  0x2c:
            return  0;
        case  0x2d:
            return  0;
        case  0x2e:
            return  2;
        case  0x2f:
            return  2;
        case  0x30:
            return  2;
        case  0x31:
            return  2;
        case  0x32:
            return  2;
        case  0x33:
            return  2;
        case  0x34:
            return  2;
        case  0x35:
            return  2;
        case  0x36:
            return  1;
        case  0x37:
            return  1;
        case  0x38:
            return  1;
        case  0x39:
            return  1;
        case  0x3a:
            return  1;
        case  0x3b:
            return  1;
        case  0x3c:
            return  1;
        case  0x3d:
            return  1;
        case  0x3e:
            return  1;
        case  0x3f:
            return  1;
        case  0x40:
            return  1;
        case  0x41:
            return  1;
        case  0x42:
            return  1;
        case  0x43:
            return  1;
        case  0x44:
            return  1;
        case  0x45:
            return  1;
        case  0x46:
            return  1;
        case  0x47:
            return  1;
        case  0x48:
            return  1;
        case  0x49:
            return  1;
        case  0x4a:
            return  1;
        case  0x4b:
            return  1;
        case  0x4c:
            return  1;
        case  0x4d:
            return  1;
        case  0x4e:
            return  1;
        case  0x4f:
            return  3;
        case  0x50:
            return  3;
        case  0x51:
            return  3;
        case  0x52:
            return  3;
        case  0x53:
            return  3;
        case  0x54:
            return  3;
        case  0x55:
            return  3;
        case  0x56:
            return  3;
        case  0x57:
            return  0;
        case  0x58:
            return  0;
        case  0x59:
            return  0;
        case  0x5a:
            return  0;
        case  0x5b:
            return  0;
        case  0x5c:
            return  0;
        case  0x5d:
            return  0;
        case  0x5e:
            return  0;
        case  0x5f:
            return  0;
        case  0x60:
            return  2;
        case  0x61:
            return  2;
        case  0x62:
            return  2;
        case  0x63:
            return  2;
        case  0x64:
            return  2;
        case  0x65:
            return  2;
        case  0x66:
            return  2;
        case  0x67:
            return  2;
        case  0x68:
            return  2;
        case  0x69:
            return  2;
        case  0x6a:
            return  2;
        case  0x6b:
            return  2;
        case  0x6c:
            return  2;
        case  0x6d:
            return  2;
        case  0x6e:
            return  2;
        case  0x6f:
            return  2;
        case  0x70:
            return  2;
        case  0x71:
            return  2;
        case  0x72:
            return  2;
        case  0x73:
            return  2;
        case  0x74:
            return  1;
        case  0x75:
            return  1;
        case  0x76:
            return  1;
        case  0x77:
            return  1;
        case  0x78:
            return  2;
        case  0x79:
            return  2;
        case  0x7a:
            return  2;
        case  0x7b:
            return  2;
        case  0x7c:
            return  2;
        case  0x7d:
            return  2;
        case  0x7e:
            return  2;
        case  0x7f:
            return  2;
        case  0x80:
            return  2;
        case  0x81:
            return  2;
        case  0x82:
            return  2;
        case  0x83:
            return  2;
        case  0x84:
            return  0;
        case  0x85:
            return  1;
        case  0x86:
            return  1;
        case  0x87:
            return  1;
        case  0x88:
            return  1;
        case  0x89:
            return  1;
        case  0x8a:
            return  1;
        case  0x8b:
            return  1;
        case  0x8c:
            return  1;
        case  0x8d:
            return  1;
        case  0x8e:
            return  1;
        case  0x8f:
            return  1;
        case  0x90:
            return  1;
        case  0x91:
            return  1;
        case  0x92:
            return  1;
        case  0x93:
            return  1;
        case  0x94:
            return  2;
        case  0x95:
            return  2;
        case  0x96:
            return  2;
        case  0x97:
            return  2;
        case  0x98:
            return  2;
        case  0x99:
            return  1;
        case  0x9a:
            return  1;
        case  0x9b:
            return  1;
        case  0x9c:
            return  1;
        case  0x9d:
            return  1;
        case  0x9e:
            return  1;
        case  0x9f:
            return  2;
        case  0xa0:
            return  2;
        case  0xa1:
            return  2;
        case  0xa2:
            return  2;
        case  0xa3:
            return  2;
        case  0xa4:
            return  2;
        case  0xa5:
            return  2;
        case  0xa6:
            return  2;
        case  0xa7:
            return  0;
        case  0xa8:
            return  0;
        case  0xa9:
            return  0;
        case  0xaa:
            return  1;
        case  0xab:
            return  1;
        case  0xac:
            return  1;
        case  0xad:
            return  1;
        case  0xae:
            return  1;
        case  0xaf:
            return  1;
        case  0xb0:
            return  1;
        case  0xb1:
            return  0;
        case  0xb2:
            return  0;
        case  0xb3:
            return  1;
        case  0xb4:
            return  1;
        case  0xb5:
            return  2;
        case  0xb6:
            return  0;
        case  0xb7:
            return  0;
        case  0xb8:
            return  0;
        case  0xb9:
            return  0;
        case  0xba:
            return  0;
        case  0xbb:
            return  0;
        case  0xbc:
            return  1;
        case  0xbd:
            return  1;
        case  0xbe:
            return  1;
        case  0xbf:
            return  1;
        case  0xc0:
            return  1;
        case  0xc1:
            return  1;
        case  0xc2:
            return  1;
        case  0xc3:
            return  1;
        case  0xc4:
            return  0;
        case  0xc5:
            return  0;
        case  0xc6:
            return  1;
        case  0xc7:
            return  1;
        case  0xc8:
            return  0;
        case  0xc9:
            return  0;
        case  0xca:
            return  0;
        case  0xfe:
            return  0;
        case  0xff:
            return  0;
        default:
            return 0;
    }

}

int jvm_opcode_pushed(u1 code)
{
    switch(code) {
        case  0x00:
            return 0;
        case  0x01:
            return 1;
        case  0x02:
            return 1;
        case  0x03:
            return 1;
        case  0x04:
            return 1;
        case  0x05:
            return 1;
        case  0x06:
            return 1;
        case  0x07:
            return 1;
        case  0x08:
            return 1;
        case  0x09:
            return 1;
        case  0x0a:
            return 1;
        case  0x0b:
            return 1;
        case  0x0c:
            return 1;
        case  0x0d:
            return 1;
        case  0x0e:
            return 1;
        case  0x0f:
            return 1;
        case  0x10:
            return 1;
        case  0x11:
            return 1;
        case  0x12:
            return 1;
        case  0x13:
            return 1;
        case  0x14:
            return 1;
        case  0x15:
            return 1;
        case  0x16:
            return 1;
        case  0x17:
            return 1;
        case  0x18:
            return 1;
        case  0x19:
            return 1;
        case  0x1a:
            return 1;
        case  0x1b:
            return 1;
        case  0x1c:
            return 1;
        case  0x1d:
            return 1;
        case  0x1e:
            return 1;
        case  0x1f:
            return 1;
        case  0x20:
            return 1;
        case  0x21:
            return 1;
        case  0x22:
            return 1;
        case  0x23:
            return 1;
        case  0x24:
            return 1;
        case  0x25:
            return 1;
        case  0x26:
            return 1;
        case  0x27:
            return 1;
        case  0x28:
            return 1;
        case  0x29:
            return 1;
        case  0x2a:
            return 1;
        case  0x2b:
            return 1;
        case  0x2c:
            return 1;
        case  0x2d:
            return 1;
        case  0x2e:
            return 1;
        case  0x2f:
            return 1;
        case  0x30:
            return 1;
        case  0x31:
            return 1;
        case  0x32:
            return 1;
        case  0x33:
            return 1;
        case  0x34:
            return 1;
        case  0x35:
            return 1;
        case  0x36:
            return 0;
        case  0x37:
            return 0;
        case  0x38:
            return 0;
        case  0x39:
            return 0;
        case  0x3a:
            return 0;
        case  0x3b:
            return 0;
        case  0x3c:
            return 0;
        case  0x3d:
            return 0;
        case  0x3e:
            return 0;
        case  0x3f:
            return 0;
        case  0x40:
            return 0;
        case  0x41:
            return 0;
        case  0x42:
            return 0;
        case  0x43:
            return 0;
        case  0x44:
            return 0;
        case  0x45:
            return 0;
        case  0x46:
            return 0;
        case  0x47:
            return 0;
        case  0x48:
            return 0;
        case  0x49:
            return 0;
        case  0x4a:
            return 0;
        case  0x4b:
            return 0;
        case  0x4c:
            return 0;
        case  0x4d:
            return 0;
        case  0x4e:
            return 0;
        case  0x4f:
            return 0;
        case  0x50:
            return 0;
        case  0x51:
            return 0;
        case  0x52:
            return 0;
        case  0x53:
            return 0;
        case  0x54:
            return 0;
        case  0x55:
            return 0;
        case  0x56:
            return 0;
        case  0x57:
            return 0;
        case  0x58:
            return 0;
        case  0x59:
            return 0;
        case  0x5a:
            return 0;
        case  0x5b:
            return 0;
        case  0x5c:
            return 0;
        case  0x5d:
            return 0;
        case  0x5e:
            return 0;
        case  0x5f:
            return 0;
        case  0x60:
            return 1;
        case  0x61:
            return 1;
        case  0x62:
            return 1;
        case  0x63:
            return 1;
        case  0x64:
            return 1;
        case  0x65:
            return 1;
        case  0x66:
            return 1;
        case  0x67:
            return 1;
        case  0x68:
            return 1;
        case  0x69:
            return 1;
        case  0x6a:
            return 1;
        case  0x6b:
            return 1;
        case  0x6c:
            return 1;
        case  0x6d:
            return 1;
        case  0x6e:
            return 1;
        case  0x6f:
            return 1;
        case  0x70:
            return 1;
        case  0x71:
            return 1;
        case  0x72:
            return 1;
        case  0x73:
            return 1;
        case  0x74:
            return 1;
        case  0x75:
            return 1;
        case  0x76:
            return 1;
        case  0x77:
            return 1;
        case  0x78:
            return 1;
        case  0x79:
            return 1;
        case  0x7a:
            return 1;
        case  0x7b:
            return 1;
        case  0x7c:
            return 1;
        case  0x7d:
            return 1;
        case  0x7e:
            return 1;
        case  0x7f:
            return 1;
        case  0x80:
            return 1;
        case  0x81:
            return 1;
        case  0x82:
            return 1;
        case  0x83:
            return 1;
        case  0x84:
            return 0;
        case  0x85:
            return 1;
        case  0x86:
            return 1;
        case  0x87:
            return 1;
        case  0x88:
            return 1;
        case  0x89:
            return 1;
        case  0x8a:
            return 1;
        case  0x8b:
            return 1;
        case  0x8c:
            return 1;
        case  0x8d:
            return 1;
        case  0x8e:
            return 1;
        case  0x8f:
            return 1;
        case  0x90:
            return 1;
        case  0x91:
            return 1;
        case  0x92:
            return 1;
        case  0x93:
            return 1;
        case  0x94:
            return 1;
        case  0x95:
            return 1;
        case  0x96:
            return 1;
        case  0x97:
            return 1;
        case  0x98:
            return 1;
        case  0x99:
            return 0;
        case  0x9a:
            return 0;
        case  0x9b:
            return 0;
        case  0x9c:
            return 0;
        case  0x9d:
            return 0;
        case  0x9e:
            return 0;
        case  0x9f:
            return 0;
        case  0xa0:
            return 0;
        case  0xa1:
            return 0;
        case  0xa2:
            return 0;
        case  0xa3:
            return 0;
        case  0xa4:
            return 0;
        case  0xa5:
            return 0;
        case  0xa6:
            return 0;
        case  0xa7:
            return 0;
        case  0xa8:
            return 0;
        case  0xa9:
            return 0;
        case  0xaa:
            return 0;
        case  0xab:
            return 0;
        case  0xac:
            return 0;
        case  0xad:
            return 0;
        case  0xae:
            return 0;
        case  0xaf:
            return 0;
        case  0xb0:
            return 0;
        case  0xb1:
            return 0;
        case  0xb2:
            return 1;
        case  0xb3:
            return 0;
        case  0xb4:
            return 1;
        case  0xb5:
            return 0;
        case  0xb6:
            return 0;
        case  0xb7:
            return 0;
        case  0xb8:
            return 0;
        case  0xb9:
            return 0;
        case  0xba:
            return 0;
        case  0xbb:
            return 1;
        case  0xbc:
            return 1;
        case  0xbd:
            return 1;
        case  0xbe:
            return 1;
        case  0xbf:
            return 1;
        case  0xc0:
            return 1;
        case  0xc1:
            return 1;
        case  0xc2:
            return 0;
        case  0xc3:
            return 0;
        case  0xc4:
            return 0;
        case  0xc5:
            return 1;
        case  0xc6:
            return 0;
        case  0xc7:
            return 0;
        case  0xc8:
            return 0;
        case  0xc9:
            return 0;
        case  0xca:
            return 0;
        case  0xfe:
            return 0;
        case  0xff:
            return 0;
        default:
            return 0;
    }
}

int jvm_opcode_param_len(u1 code)
{
    switch(code) {
        case  0x00:
        case  0x01:
        case  0x02:
        case  0x03:
        case  0x04:
        case  0x05:
        case  0x06:
        case  0x07:
        case  0x08:
        case  0x09:
        case  0x0a:
        case  0x0b:
        case  0x0c:
        case  0x0d:
        case  0x0e:
        case  0x0f:
            return  0;
        case  0x10:
            return  1;
        case  0x11:
            return  2;
        case  0x12:
            return  1;
        case  0x13:
        case  0x14:
            return  2;
        case  0x15:
        case  0x16:
        case  0x17:
        case  0x18:
        case  0x19:
            return  1;
        case  0x1a:
        case  0x1b:
        case  0x1c:
        case  0x1d:
        case  0x1e:
        case  0x1f:
        case  0x20:
        case  0x21:
        case  0x22:
        case  0x23:
        case  0x24:
        case  0x25:
        case  0x26:
        case  0x27:
        case  0x28:
        case  0x29:
        case  0x2a:
        case  0x2b:
        case  0x2c:
        case  0x2d:
        case  0x2e:
        case  0x2f:
        case  0x30:
        case  0x31:
        case  0x32:
        case  0x33:
        case  0x34:
        case  0x35:
            return  0;
        case  0x36:
        case  0x37:
        case  0x38:
        case  0x39:
        case  0x3a:
            return  1;
        case  0x3b:
        case  0x3c:
        case  0x3d:
        case  0x3e:
        case  0x3f:
        case  0x40:
        case  0x41:
        case  0x42:
        case  0x43:
        case  0x44:
        case  0x45:
        case  0x46:
        case  0x47:
        case  0x48:
        case  0x49:
        case  0x4a:
        case  0x4b:
        case  0x4c:
        case  0x4d:
        case  0x4e:
        case  0x4f:
        case  0x50:
        case  0x51:
        case  0x52:
        case  0x53:
        case  0x54:
        case  0x55:
        case  0x56:
        case  0x57:
        case  0x58:
        case  0x59:
        case  0x5a:
        case  0x5b:
        case  0x5c:
        case  0x5d:
        case  0x5e:
        case  0x5f:
        case  0x60:
        case  0x61:
        case  0x62:
        case  0x63:
        case  0x64:
        case  0x65:
        case  0x66:
        case  0x67:
        case  0x68:
        case  0x69:
        case  0x6a:
        case  0x6b:
        case  0x6c:
        case  0x6d:
        case  0x6e:
        case  0x6f:
        case  0x70:
        case  0x71:
        case  0x72:
        case  0x73:
        case  0x74:
        case  0x75:
        case  0x76:
        case  0x77:
        case  0x78:
        case  0x79:
        case  0x7a:
        case  0x7b:
        case  0x7c:
        case  0x7d:
        case  0x7e:
        case  0x7f:
        case  0x80:
        case  0x81:
        case  0x82:
        case  0x83:
            return  0;
        case  0x84:
            return  2;
        case  0x85:
        case  0x86:
        case  0x87:
        case  0x88:
        case  0x89:
        case  0x8a:
        case  0x8b:
        case  0x8c:
        case  0x8d:
        case  0x8e:
        case  0x8f:
        case  0x90:
        case  0x91:
        case  0x92:
        case  0x93:
        case  0x94:
        case  0x95:
        case  0x96:
        case  0x97:
        case  0x98:
            return  0;
        case  0x99:
        case  0x9a:
        case  0x9b:
        case  0x9c:
        case  0x9d:
        case  0x9e:
        case  0x9f:
        case  0xa0:
        case  0xa1:
        case  0xa2:
        case  0xa3:
        case  0xa4:
        case  0xa5:
        case  0xa6:
        case  0xa7:
        case  0xa8:
            return  2;
        case  0xa9:
            return  1;
        case  0xaa:
            return  16;
        case  0xab:
            return  8;
        case  0xac:
        case  0xad:
        case  0xae:
        case  0xaf:
        case  0xb0:
        case  0xb1:
            return  0;
        case  0xb2:
        case  0xb3:
        case  0xb4:
        case  0xb5:
        case  0xb6:
        case  0xb7:
        case  0xb8:
            return  2;
        case  0xb9:
        case  0xba:
            return  4;
        case  0xbb:
            return  2;
        case  0xbc:
            return  1;
        case  0xbd:
            return  2;
        case  0xbe:
        case  0xbf:
            return  0;
        case  0xc0:
        case  0xc1:
            return  2;
        case  0xc2:
        case  0xc3:
            return  0;
        case  0xc4:
        case  0xc5:
            return  3;
        case  0xc6:
        case  0xc7:
            return  2;
        case  0xc8:
        case  0xc9:
            return  4;
        case  0xca:
        case  0xfe:
        case  0xff:
            return  0;
        default:
            return 0;
    }
}

int get_opcode_popped(jclass_file *jc, u1 code)
{
    return jvm_opcode_popped(code);
}

int get_opcode_pushed(jclass_file *jc, u1 code)
{
    return jvm_opcode_pushed(code);
}

int get_opcode_param_length(jclass_file *jc, u1 code)
{
    return jvm_opcode_param_len(code);
}

char* get_opcode_name(jclass_file *jc, u1 code)
{
    return jvm_opcode_name(code);
}
